/*
 * CombatListJFrame.java
 *
 * Created on __DATE__, __TIME__
 */

package com.sdk.realm.combat.ui;

/**
 *
 * @author  __USER__
 */
public class CombatListJFrame extends javax.swing.JFrame {

	private CombatListFrameController _myController;

	/** Creates new form CombatListJFrame */
	public CombatListJFrame() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
//GEN-BEGIN:initComponents
// <editor-fold defaultstate="collapsed" desc="Generated Code">
private void initComponents() {

jLabel1 = new javax.swing.JLabel();
jScrollPane1 = new javax.swing.JScrollPane();
combatListJTable = new javax.swing.JTable();
deleteCombatJButton = new javax.swing.JButton();
openCombatJButton = new javax.swing.JButton();
addCombatJButton = new javax.swing.JButton();
jLabel2 = new javax.swing.JLabel();

jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18));
jLabel1.setText("Combat Encounter List");

combatListJTable.setModel(new CombatListTableDataModel());
jScrollPane1.setViewportView(combatListJTable);

deleteCombatJButton.setText("Delete");
deleteCombatJButton.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
deleteCombatJButtonActionPerformed(evt);
}
});

openCombatJButton.setText("Open");
openCombatJButton.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
openCombatJButtonActionPerformed(evt);
}
});

addCombatJButton.setText("Add");
addCombatJButton.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
addCombatJButtonActionPerformed(evt);
}
});

jLabel2.setText("To add an encounter, click the Add button and type in a description");

org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
getContentPane().setLayout(layout);
layout.setHorizontalGroup(
layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
.add(layout.createSequentialGroup()
.add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
.add(layout.createSequentialGroup()
.addContainerGap()
.add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 635, Short.MAX_VALUE))
.add(layout.createSequentialGroup()
.add(23, 23, 23)
.add(addCombatJButton)
.add(18, 18, 18)
.add(openCombatJButton)
.add(18, 18, 18)
.add(deleteCombatJButton)
.add(18, 18, 18)
.add(jLabel2))
.add(layout.createSequentialGroup()
.add(202, 202, 202)
.add(jLabel1)))
.addContainerGap())
);
layout.setVerticalGroup(
layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
.add(layout.createSequentialGroup()
.add(4, 4, 4)
.add(jLabel1)
.add(18, 18, 18)
.add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 249, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
.add(18, 18, 18)
.add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
.add(addCombatJButton)
.add(openCombatJButton)
.add(deleteCombatJButton)
.add(jLabel2))
.addContainerGap(13, Short.MAX_VALUE))
);

pack();
}// </editor-fold>
//GEN-END:initComponents

	private void addCombatJButtonActionPerformed(java.awt.event.ActionEvent evt) {
		_myController.addCombatJButtonClicked();
	}

	private void deleteCombatJButtonActionPerformed(
			java.awt.event.ActionEvent evt) {
		_myController.deleteCombatJButtonClicked();
	}

	private void openCombatJButtonActionPerformed(java.awt.event.ActionEvent evt) {
		_myController.openCombatJButtonClicked();
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new CombatListJFrame().setVisible(true);
			}
		});
	}

//GEN-BEGIN:variables
// Variables declaration - do not modify
private javax.swing.JButton addCombatJButton;
private javax.swing.JTable combatListJTable;
private javax.swing.JButton deleteCombatJButton;
private javax.swing.JLabel jLabel1;
private javax.swing.JLabel jLabel2;
private javax.swing.JScrollPane jScrollPane1;
private javax.swing.JButton openCombatJButton;
// End of variables declaration//GEN-END:variables

	javax.swing.JTable getCombatListJTable() {
		return combatListJTable;
	}

	CombatListTableDataModel getTableDataModel() {

		return (CombatListTableDataModel) combatListJTable.getModel();
	}

	public void setController(CombatListFrameController aController) {
		_myController = aController;
		getTableDataModel().setMyFrameController(aController);
	}

}