/*
 * WillContestListJFrame.java
 *
 * Created on __DATE__, __TIME__
 */

package com.sdk.realm.willcontest.ui;

import com.sdk.realm.combat.ui.CombatListFrameController;
import com.sdk.realm.combat.ui.CombatListTableDataModel;

/**
 *
 * @author  __USER__
 */
public class WillContestListJFrame extends javax.swing.JFrame {

	private WillContestListFrameController myController;

	/** Creates new form WillContestListJFrame */
	public WillContestListJFrame() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		willContestListJTable = new javax.swing.JTable();
		createContestJButton = new javax.swing.JButton();
		openContestJButton = new javax.swing.JButton();
		deleteContestJButton = new javax.swing.JButton();
		deleteAllContestsJButton = new javax.swing.JButton();

		jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18));
		jLabel1.setText("Will Contest List");

		willContestListJTable.setModel(new WillContestListTableDataModel());
		jScrollPane1.setViewportView(willContestListJTable);

		createContestJButton.setText("Create Contest");
		createContestJButton
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						createContestJButtonActionPerformed(evt);
					}
				});

		openContestJButton.setText("Open Contest");
		openContestJButton
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						openContestJButtonActionPerformed(evt);
					}
				});

		deleteContestJButton.setText("Delete Contest");
		deleteContestJButton
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						deleteContestJButtonActionPerformed(evt);
					}
				});

		deleteAllContestsJButton.setText("Delete All Contests");
		deleteAllContestsJButton
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						deleteAllContestsJButtonActionPerformed(evt);
					}
				});

		org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(
				layout.createSequentialGroup().addContainerGap().add(
						jScrollPane1,
						org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 621,
						Short.MAX_VALUE).addContainerGap()).add(
				layout.createSequentialGroup().add(47, 47, 47).add(
						createContestJButton).add(18, 18, 18).add(
						openContestJButton).add(18, 18, 18).add(
						deleteContestJButton).add(18, 18, 18).add(
						deleteAllContestsJButton).addContainerGap(106,
						Short.MAX_VALUE)).add(
				org.jdesktop.layout.GroupLayout.TRAILING,
				layout.createSequentialGroup().addContainerGap(254,
						Short.MAX_VALUE).add(jLabel1).add(243, 243, 243)));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								layout
										.createSequentialGroup()
										.addContainerGap()
										.add(jLabel1)
										.add(18, 18, 18)
										.add(
												jScrollPane1,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												258,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												org.jdesktop.layout.LayoutStyle.UNRELATED)
										.add(
												layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.BASELINE)
														.add(
																createContestJButton)
														.add(openContestJButton)
														.add(
																deleteContestJButton)
														.add(
																deleteAllContestsJButton))
										.addContainerGap(
												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void deleteAllContestsJButtonActionPerformed(
			java.awt.event.ActionEvent evt) {
		myController.deleteAllWillContestsJButtonClicked();
	}

	private void deleteContestJButtonActionPerformed(
			java.awt.event.ActionEvent evt) {
		myController.deleteWillContestJButtonClicked();
	}

	private void openContestJButtonActionPerformed(
			java.awt.event.ActionEvent evt) {
		myController.openContestJButtonClicked();
	}

	private void createContestJButtonActionPerformed(
			java.awt.event.ActionEvent evt) {
		myController.createContestJButtonClicked();
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new WillContestListJFrame().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton createContestJButton;
	private javax.swing.JButton deleteAllContestsJButton;
	private javax.swing.JButton deleteContestJButton;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JButton openContestJButton;
	private javax.swing.JTable willContestListJTable;

	// End of variables declaration//GEN-END:variables

	javax.swing.JTable getWillContestListJTable() {
		return willContestListJTable;
	}

	WillContestListTableDataModel getTableDataModel() {

		return (WillContestListTableDataModel) willContestListJTable.getModel();
	}

	public void setController(WillContestListFrameController aController) {
		myController = aController;
		getTableDataModel().setMyFrameController(aController);
	}

}