//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.09.05 at 09:33:40 PM CDT 
//


package com.sdk.realm.willcontest.persistance;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.sdk.realm.willcontest.persistance package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _WillContestLibrary_QNAME = new QName("http://com.sdk.realm/RealmWillContestConsequencesDefinitionV0.0.0.1", "WillContestLibrary");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.sdk.realm.willcontest.persistance
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link WillContestRoundType }
     * 
     */
    public WillContestRoundType createWillContestRoundType() {
        return new WillContestRoundType();
    }

    /**
     * Create an instance of {@link WillContestantType }
     * 
     */
    public WillContestantType createWillContestantType() {
        return new WillContestantType();
    }

    /**
     * Create an instance of {@link DiceRollRangeType }
     * 
     */
    public DiceRollRangeType createDiceRollRangeType() {
        return new DiceRollRangeType();
    }

    /**
     * Create an instance of {@link WillContestCollectionType }
     * 
     */
    public WillContestCollectionType createWillContestCollectionType() {
        return new WillContestCollectionType();
    }

    /**
     * Create an instance of {@link WillContestRoundCollectionType }
     * 
     */
    public WillContestRoundCollectionType createWillContestRoundCollectionType() {
        return new WillContestRoundCollectionType();
    }

    /**
     * Create an instance of {@link WillContestLibraryType }
     * 
     */
    public WillContestLibraryType createWillContestLibraryType() {
        return new WillContestLibraryType();
    }

    /**
     * Create an instance of {@link WillContestType }
     * 
     */
    public WillContestType createWillContestType() {
        return new WillContestType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link WillContestLibraryType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.sdk.realm/RealmWillContestConsequencesDefinitionV0.0.0.1", name = "WillContestLibrary")
    public JAXBElement<WillContestLibraryType> createWillContestLibrary(WillContestLibraryType value) {
        return new JAXBElement<WillContestLibraryType>(_WillContestLibrary_QNAME, WillContestLibraryType.class, null, value);
    }

}
