//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.09.05 at 09:33:40 PM CDT 
//


package com.sdk.realm.willcontest.persistance;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for WillContestRoundType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WillContestRoundType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RoundNumber" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="ContestantOneTotalWill" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="ContestantTwoTotalWill" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="ConsequenceValue" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="ConsequenceDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ContestantOnePermanentModifier" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="ContestantOneTemporarytModifier" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="ContestantOneTemporaryModifierExpirationRound" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WillContestRoundType", propOrder = {
    "roundNumber",
    "contestantOneTotalWill",
    "contestantTwoTotalWill",
    "consequenceValue",
    "consequenceDescription",
    "contestantOnePermanentModifier",
    "contestantOneTemporarytModifier",
    "contestantOneTemporaryModifierExpirationRound",
    "id"
})
public class WillContestRoundType {

    @XmlElement(name = "RoundNumber")
    protected int roundNumber;
    @XmlElement(name = "ContestantOneTotalWill")
    protected int contestantOneTotalWill;
    @XmlElement(name = "ContestantTwoTotalWill")
    protected int contestantTwoTotalWill;
    @XmlElement(name = "ConsequenceValue")
    protected int consequenceValue;
    @XmlElement(name = "ConsequenceDescription", required = true)
    protected String consequenceDescription;
    @XmlElement(name = "ContestantOnePermanentModifier")
    protected int contestantOnePermanentModifier;
    @XmlElement(name = "ContestantOneTemporarytModifier")
    protected int contestantOneTemporarytModifier;
    @XmlElement(name = "ContestantOneTemporaryModifierExpirationRound")
    protected int contestantOneTemporaryModifierExpirationRound;
    @XmlElement(name = "Id")
    protected int id;

    /**
     * Gets the value of the roundNumber property.
     * 
     */
    public int getRoundNumber() {
        return roundNumber;
    }

    /**
     * Sets the value of the roundNumber property.
     * 
     */
    public void setRoundNumber(int value) {
        this.roundNumber = value;
    }

    /**
     * Gets the value of the contestantOneTotalWill property.
     * 
     */
    public int getContestantOneTotalWill() {
        return contestantOneTotalWill;
    }

    /**
     * Sets the value of the contestantOneTotalWill property.
     * 
     */
    public void setContestantOneTotalWill(int value) {
        this.contestantOneTotalWill = value;
    }

    /**
     * Gets the value of the contestantTwoTotalWill property.
     * 
     */
    public int getContestantTwoTotalWill() {
        return contestantTwoTotalWill;
    }

    /**
     * Sets the value of the contestantTwoTotalWill property.
     * 
     */
    public void setContestantTwoTotalWill(int value) {
        this.contestantTwoTotalWill = value;
    }

    /**
     * Gets the value of the consequenceValue property.
     * 
     */
    public int getConsequenceValue() {
        return consequenceValue;
    }

    /**
     * Sets the value of the consequenceValue property.
     * 
     */
    public void setConsequenceValue(int value) {
        this.consequenceValue = value;
    }

    /**
     * Gets the value of the consequenceDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConsequenceDescription() {
        return consequenceDescription;
    }

    /**
     * Sets the value of the consequenceDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConsequenceDescription(String value) {
        this.consequenceDescription = value;
    }

    /**
     * Gets the value of the contestantOnePermanentModifier property.
     * 
     */
    public int getContestantOnePermanentModifier() {
        return contestantOnePermanentModifier;
    }

    /**
     * Sets the value of the contestantOnePermanentModifier property.
     * 
     */
    public void setContestantOnePermanentModifier(int value) {
        this.contestantOnePermanentModifier = value;
    }

    /**
     * Gets the value of the contestantOneTemporarytModifier property.
     * 
     */
    public int getContestantOneTemporarytModifier() {
        return contestantOneTemporarytModifier;
    }

    /**
     * Sets the value of the contestantOneTemporarytModifier property.
     * 
     */
    public void setContestantOneTemporarytModifier(int value) {
        this.contestantOneTemporarytModifier = value;
    }

    /**
     * Gets the value of the contestantOneTemporaryModifierExpirationRound property.
     * 
     */
    public int getContestantOneTemporaryModifierExpirationRound() {
        return contestantOneTemporaryModifierExpirationRound;
    }

    /**
     * Sets the value of the contestantOneTemporaryModifierExpirationRound property.
     * 
     */
    public void setContestantOneTemporaryModifierExpirationRound(int value) {
        this.contestantOneTemporaryModifierExpirationRound = value;
    }

    /**
     * Gets the value of the id property.
     * 
     */
    public int getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(int value) {
        this.id = value;
    }

}
