//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.09.05 at 09:33:40 PM CDT 
//


package com.sdk.realm.willcontest.persistance;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *         		This is a definition of the severity of the hit. The
 *         		severity increases as the letters progress in the
 *         		alphabet.
 *         	
 * 
 * <p>Java class for WillContestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WillContestType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="ContestantOne" type="{http://com.sdk.realm/RealmWillContestConsequencesDefinitionV0.0.0.1}WillContestantType"/>
 *         &lt;element name="ContestantTwo" type="{http://com.sdk.realm/RealmWillContestConsequencesDefinitionV0.0.0.1}WillContestantType"/>
 *         &lt;element name="Rounds" type="{http://com.sdk.realm/RealmWillContestConsequencesDefinitionV0.0.0.1}WillContestRoundCollectionType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WillContestType", propOrder = {
    "id",
    "contestantOne",
    "contestantTwo",
    "rounds"
})
public class WillContestType {

    @XmlElement(name = "Id")
    protected int id;
    @XmlElement(name = "ContestantOne", required = true)
    protected WillContestantType contestantOne;
    @XmlElement(name = "ContestantTwo", required = true)
    protected WillContestantType contestantTwo;
    @XmlElement(name = "Rounds", required = true)
    protected WillContestRoundCollectionType rounds;

    /**
     * Gets the value of the id property.
     * 
     */
    public int getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(int value) {
        this.id = value;
    }

    /**
     * Gets the value of the contestantOne property.
     * 
     * @return
     *     possible object is
     *     {@link WillContestantType }
     *     
     */
    public WillContestantType getContestantOne() {
        return contestantOne;
    }

    /**
     * Sets the value of the contestantOne property.
     * 
     * @param value
     *     allowed object is
     *     {@link WillContestantType }
     *     
     */
    public void setContestantOne(WillContestantType value) {
        this.contestantOne = value;
    }

    /**
     * Gets the value of the contestantTwo property.
     * 
     * @return
     *     possible object is
     *     {@link WillContestantType }
     *     
     */
    public WillContestantType getContestantTwo() {
        return contestantTwo;
    }

    /**
     * Sets the value of the contestantTwo property.
     * 
     * @param value
     *     allowed object is
     *     {@link WillContestantType }
     *     
     */
    public void setContestantTwo(WillContestantType value) {
        this.contestantTwo = value;
    }

    /**
     * Gets the value of the rounds property.
     * 
     * @return
     *     possible object is
     *     {@link WillContestRoundCollectionType }
     *     
     */
    public WillContestRoundCollectionType getRounds() {
        return rounds;
    }

    /**
     * Sets the value of the rounds property.
     * 
     * @param value
     *     allowed object is
     *     {@link WillContestRoundCollectionType }
     *     
     */
    public void setRounds(WillContestRoundCollectionType value) {
        this.rounds = value;
    }

}
