//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.04.10 at 04:15:49 PM CDT 
//


package com.sdk.realm.item.persistance;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ItemLibraryType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ItemLibraryType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ItemCollection" type="{http://com.sdk.realm/RealmItem-v0.0.0.1}ItemCollectionType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ItemLibraryType", propOrder = {
    "itemCollection"
})
public class ItemLibraryType {

    @XmlElement(name = "ItemCollection", required = true)
    protected ItemCollectionType itemCollection;

    /**
     * Gets the value of the itemCollection property.
     * 
     * @return
     *     possible object is
     *     {@link ItemCollectionType }
     *     
     */
    public ItemCollectionType getItemCollection() {
        return itemCollection;
    }

    /**
     * Sets the value of the itemCollection property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItemCollectionType }
     *     
     */
    public void setItemCollection(ItemCollectionType value) {
        this.itemCollection = value;
    }

}
