//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.07.16 at 04:34:17 PM CDT 
//


package com.sdk.realm.herblore.persistance;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for HerbLibraryType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HerbLibraryType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="HerbCollection" type="{http://com.sdk.realm/RealmHerbLoreDefinitionV0.0.0.1}HerbCollectionType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HerbLibraryType", propOrder = {
    "herbCollection"
})
public class HerbLibraryType {

    @XmlElement(name = "HerbCollection", required = true)
    protected HerbCollectionType herbCollection;

    /**
     * Gets the value of the herbCollection property.
     * 
     * @return
     *     possible object is
     *     {@link HerbCollectionType }
     *     
     */
    public HerbCollectionType getHerbCollection() {
        return herbCollection;
    }

    /**
     * Sets the value of the herbCollection property.
     * 
     * @param value
     *     allowed object is
     *     {@link HerbCollectionType }
     *     
     */
    public void setHerbCollection(HerbCollectionType value) {
        this.herbCollection = value;
    }

}
