/*
 * RealmApplicationLauncherJFrame.java
 *
 * Created on __DATE__, __TIME__
 */

package com.sdk.realm.application;

/**
 *
 * @author  __USER__
 */
public class RealmApplicationLauncherJFrame extends javax.swing.JFrame {

	private RealmApplicationLauncherController _myController = null;

	/** Creates new form RealmApplicationLauncherJFrame */
	public RealmApplicationLauncherJFrame() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		criticalHitsJButton = new javax.swing.JButton();
		resistanceTableJButton = new javax.swing.JButton();
		dieRollerJButton = new javax.swing.JButton();
		playerjButton = new javax.swing.JButton();
		herbLoreJButton = new javax.swing.JButton();
		characterListJButton = new javax.swing.JButton();
		combatJButton = new javax.swing.JButton();
		itemListJButton = new javax.swing.JButton();
		willContestListJButton = new javax.swing.JButton();
		movementManeuversListJButton = new javax.swing.JButton();
		applicationJMenuBar = new javax.swing.JMenuBar();
		helpjMenu = new javax.swing.JMenu();
		versionJMenuItem = new javax.swing.JMenuItem();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18));
		jLabel1.setText("Stevieware Application Launcher");

		criticalHitsJButton.setText("Critical Hits");
		criticalHitsJButton
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						criticalHitsJButtonActionPerformed(evt);
					}
				});

		resistanceTableJButton.setText("Resistance Table");
		resistanceTableJButton
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						resistanceTableJButtonActionPerformed(evt);
					}
				});

		dieRollerJButton.setText("Die Roller");
		dieRollerJButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				dieRollerJButtonActionPerformed(evt);
			}
		});

		playerjButton.setText("Players");
		playerjButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				playerjButtonActionPerformed(evt);
			}
		});

		herbLoreJButton.setText("Herb Lore");
		herbLoreJButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				herbLoreJButtonActionPerformed(evt);
			}
		});

		characterListJButton.setText("Character List");
		characterListJButton
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						characterListJButtonActionPerformed(evt);
					}
				});

		combatJButton.setText("Combat");
		combatJButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				combatJButtonActionPerformed(evt);
			}
		});

		itemListJButton.setText("Item List");
		itemListJButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				itemListJButtonActionPerformed(evt);
			}
		});

		willContestListJButton.setText("Will Contest List");
		willContestListJButton
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						willContestListJButtonActionPerformed(evt);
					}
				});

		movementManeuversListJButton.setText("Movement Maneuvers");
		movementManeuversListJButton
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						movementManeuversListJButtonActionPerformed(evt);
					}
				});

		helpjMenu.setText("Help");

		versionJMenuItem.setText("Version");
		versionJMenuItem.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				versionJMenuItemActionPerformed(evt);
			}
		});
		helpjMenu.add(versionJMenuItem);

		applicationJMenuBar.add(helpjMenu);

		setJMenuBar(applicationJMenuBar);

		org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								layout
										.createSequentialGroup()
										.addContainerGap()
										.add(
												layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.LEADING)
														.add(
																org.jdesktop.layout.GroupLayout.TRAILING,
																layout
																		.createSequentialGroup()
																		.add(
																				jLabel1)
																		.add(
																				79,
																				79,
																				79))
														.add(
																org.jdesktop.layout.GroupLayout.TRAILING,
																layout
																		.createSequentialGroup()
																		.add(
																				layout
																						.createParallelGroup(
																								org.jdesktop.layout.GroupLayout.TRAILING)
																						.add(
																								org.jdesktop.layout.GroupLayout.LEADING,
																								combatJButton,
																								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																								115,
																								Short.MAX_VALUE)
																						.add(
																								org.jdesktop.layout.GroupLayout.LEADING,
																								characterListJButton,
																								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																								115,
																								Short.MAX_VALUE)
																						.add(
																								org.jdesktop.layout.GroupLayout.LEADING,
																								playerjButton,
																								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																								115,
																								Short.MAX_VALUE)
																						.add(
																								org.jdesktop.layout.GroupLayout.LEADING,
																								criticalHitsJButton,
																								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																								115,
																								Short.MAX_VALUE)
																						.add(
																								org.jdesktop.layout.GroupLayout.LEADING,
																								dieRollerJButton,
																								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																								115,
																								Short.MAX_VALUE)
																						.add(
																								org.jdesktop.layout.GroupLayout.LEADING,
																								resistanceTableJButton,
																								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																								115,
																								Short.MAX_VALUE)
																						.add(
																								org.jdesktop.layout.GroupLayout.LEADING,
																								herbLoreJButton,
																								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																								115,
																								Short.MAX_VALUE))
																		.add(
																				103,
																				103,
																				103)
																		.add(
																				layout
																						.createParallelGroup(
																								org.jdesktop.layout.GroupLayout.LEADING,
																								false)
																						.add(
																								movementManeuversListJButton,
																								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																								Short.MAX_VALUE)
																						.add(
																								willContestListJButton,
																								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																								Short.MAX_VALUE)
																						.add(
																								itemListJButton,
																								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																								Short.MAX_VALUE))
																		.add(
																				89,
																				89,
																				89)))));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								layout
										.createSequentialGroup()
										.addContainerGap()
										.add(jLabel1)
										.add(21, 21, 21)
										.add(
												layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.BASELINE)
														.add(
																criticalHitsJButton)
														.add(itemListJButton))
										.addPreferredGap(
												org.jdesktop.layout.LayoutStyle.UNRELATED)
										.add(
												layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.BASELINE)
														.add(
																resistanceTableJButton)
														.add(
																willContestListJButton))
										.addPreferredGap(
												org.jdesktop.layout.LayoutStyle.UNRELATED)
										.add(
												layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.BASELINE)
														.add(dieRollerJButton)
														.add(
																movementManeuversListJButton))
										.add(11, 11, 11)
										.add(herbLoreJButton)
										.addPreferredGap(
												org.jdesktop.layout.LayoutStyle.UNRELATED)
										.add(playerjButton)
										.add(13, 13, 13)
										.add(characterListJButton)
										.addPreferredGap(
												org.jdesktop.layout.LayoutStyle.UNRELATED)
										.add(combatJButton).addContainerGap(33,
												Short.MAX_VALUE)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void movementManeuversListJButtonActionPerformed(
			java.awt.event.ActionEvent evt) {
		_myController.launchMovementManeuverApplication();
	}

	private void willContestListJButtonActionPerformed(
			java.awt.event.ActionEvent evt) {
		_myController.launchWillContestListApplication();
	}

	private void itemListJButtonActionPerformed(java.awt.event.ActionEvent evt) {
		_myController.launchItemListApplication();
	}

	private void combatJButtonActionPerformed(java.awt.event.ActionEvent evt) {
		_myController.launchCombatApplication();
	}

	private void characterListJButtonActionPerformed(
			java.awt.event.ActionEvent evt) {
		_myController.launchCharacterListApplication();
	}

	private void herbLoreJButtonActionPerformed(java.awt.event.ActionEvent evt) {
		_myController.launchHerbLoreApplication();
	}

	private void playerjButtonActionPerformed(java.awt.event.ActionEvent evt) {
		_myController.launchPlayerApplication();
	}

	private void versionJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {
		_myController.displayVersion();
	}

	private void dieRollerJButtonActionPerformed(java.awt.event.ActionEvent evt) {
		_myController.launchDieRollerApplication();
	}

	private void criticalHitsJButtonActionPerformed(
			java.awt.event.ActionEvent evt) {
		_myController.launchCriticalHitsApplication();
	}

	private void resistanceTableJButtonActionPerformed(
			java.awt.event.ActionEvent evt) {
		_myController.launchResistanceTableApplication();
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new RealmApplicationLauncherJFrame().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JMenuBar applicationJMenuBar;
	private javax.swing.JButton characterListJButton;
	private javax.swing.JButton combatJButton;
	private javax.swing.JButton criticalHitsJButton;
	private javax.swing.JButton dieRollerJButton;
	private javax.swing.JMenu helpjMenu;
	private javax.swing.JButton herbLoreJButton;
	private javax.swing.JButton itemListJButton;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JButton movementManeuversListJButton;
	private javax.swing.JButton playerjButton;
	private javax.swing.JButton resistanceTableJButton;
	private javax.swing.JMenuItem versionJMenuItem;
	private javax.swing.JButton willContestListJButton;

	// End of variables declaration//GEN-END:variables

	public void setController(RealmApplicationLauncherController aController) {
		_myController = aController;
	}

}