/*
 * HerbLoreJFrame.java
 *
 * Created on __DATE__, __TIME__
 */

package com.sdk.realm.herblore.ui;

/**
 *
 * @author  __USER__
 */
public class HerbLoreJFrame extends javax.swing.JFrame {

	private HerbLoreFrameController _myController = null;

	/** Creates new form HerbLoreJFrame */
	public HerbLoreJFrame() {
		initComponents();
	}

	public HerbLoreJFrame(HerbLoreFrameController aController) {
		_myController = aController;
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jScrollPane1 = new javax.swing.JScrollPane();
		jTable1 = new javax.swing.JTable();
		jLabel1 = new javax.swing.JLabel();
		jPanel1 = new javax.swing.JPanel();
		searchByClassificationJButton = new javax.swing.JButton();
		jLabel2 = new javax.swing.JLabel();
		searchByNameJButton = new javax.swing.JButton();
		surpriseSearchJButton = new javax.swing.JButton();
		searchCriteriaJTextField = new javax.swing.JTextField();
		jLabel3 = new javax.swing.JLabel();
		jPanel2 = new javax.swing.JPanel();
		jScrollPane2 = new javax.swing.JScrollPane();
		searchResultsJTable = new javax.swing.JTable();
		jPanel3 = new javax.swing.JPanel();
		jLabel5 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		jLabel8 = new javax.swing.JLabel();
		jLabel9 = new javax.swing.JLabel();
		jLabel10 = new javax.swing.JLabel();
		resultNameJTextField = new javax.swing.JTextField();
		resultClassificationJTextField = new javax.swing.JTextField();
		attackLevelJTextField = new javax.swing.JTextField();
		formAndPreperationJTextField = new javax.swing.JTextField();
		costAndRarityJTextField = new javax.swing.JTextField();
		jScrollPane3 = new javax.swing.JScrollPane();
		effectJTextArea = new javax.swing.JTextArea();
		jLabel4 = new javax.swing.JLabel();

		jTable1.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null } }, new String[] { "Title 1",
						"Title 2", "Title 3", "Title 4" }));
		jScrollPane1.setViewportView(jTable1);

		jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18));
		jLabel1.setText("Herb Lore");

		jPanel1.setBorder(javax.swing.BorderFactory
				.createLineBorder(new java.awt.Color(0, 0, 0)));

		searchByClassificationJButton.setText("Classification");
		searchByClassificationJButton
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						searchByClassificationJButtonActionPerformed(evt);
					}
				});

		jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11));
		jLabel2.setText("Search by:");

		searchByNameJButton.setText("Name");
		searchByNameJButton
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						searchByNameJButtonActionPerformed(evt);
					}
				});

		surpriseSearchJButton.setText("Surprise me!");
		surpriseSearchJButton
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						surpriseSearchJButtonActionPerformed(evt);
					}
				});

		searchCriteriaJTextField.setText("Antidotes");

		org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								jPanel1Layout
										.createSequentialGroup()
										.addContainerGap()
										.add(
												jPanel1Layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.LEADING)
														.add(
																org.jdesktop.layout.GroupLayout.TRAILING,
																jPanel1Layout
																		.createSequentialGroup()
																		.add(
																				searchCriteriaJTextField,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																				301,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				org.jdesktop.layout.LayoutStyle.RELATED,
																				55,
																				Short.MAX_VALUE)
																		.add(
																				jPanel1Layout
																						.createParallelGroup(
																								org.jdesktop.layout.GroupLayout.LEADING,
																								false)
																						.add(
																								surpriseSearchJButton)
																						.add(
																								searchByClassificationJButton,
																								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																								Short.MAX_VALUE)
																						.add(
																								searchByNameJButton,
																								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																								Short.MAX_VALUE))
																		.addContainerGap())
														.add(
																org.jdesktop.layout.GroupLayout.TRAILING,
																jPanel1Layout
																		.createSequentialGroup()
																		.add(
																				jLabel2)
																		.add(
																				37,
																				37,
																				37)))));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								jPanel1Layout
										.createSequentialGroup()
										.addContainerGap()
										.add(jLabel2)
										.addPreferredGap(
												org.jdesktop.layout.LayoutStyle.RELATED)
										.add(searchByNameJButton)
										.addPreferredGap(
												org.jdesktop.layout.LayoutStyle.RELATED)
										.add(
												jPanel1Layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.LEADING)
														.add(
																searchCriteriaJTextField,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
														.add(
																jPanel1Layout
																		.createSequentialGroup()
																		.add(
																				searchByClassificationJButton)
																		.addPreferredGap(
																				org.jdesktop.layout.LayoutStyle.RELATED)
																		.add(
																				surpriseSearchJButton)))
										.addContainerGap(
												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));

		jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14));
		jLabel3.setText("Search criteria:");

		jPanel2.setBorder(javax.swing.BorderFactory
				.createLineBorder(new java.awt.Color(0, 0, 0)));

		searchResultsJTable
				.setModel(_myController.getSearchResultsTableModel());
		searchResultsJTable.setSelectionModel(_myController
				.getResultsTableListSelectionModel());
		jScrollPane2.setViewportView(searchResultsJTable);

		jPanel3.setBorder(javax.swing.BorderFactory
				.createLineBorder(new java.awt.Color(0, 0, 0)));

		jLabel5.setText("Name:");

		jLabel6.setText("Classification:");

		jLabel7.setText("Attack Level:");

		jLabel8.setText("Form & Preperation:");

		jLabel9.setText("Cost & Rarity:");

		jLabel10.setText("Effect:");

		resultNameJTextField.setEditable(false);
		resultNameJTextField.setText(" ");

		resultClassificationJTextField.setEditable(false);
		resultClassificationJTextField.setText(" ");

		attackLevelJTextField.setEditable(false);
		attackLevelJTextField.setText(" ");

		formAndPreperationJTextField.setEditable(false);
		formAndPreperationJTextField.setText(" ");

		costAndRarityJTextField.setEditable(false);
		costAndRarityJTextField.setText(" ");

		effectJTextArea.setColumns(20);
		effectJTextArea.setEditable(false);
		effectJTextArea.setLineWrap(true);
		effectJTextArea.setRows(5);
		effectJTextArea.setWrapStyleWord(true);
		jScrollPane3.setViewportView(effectJTextArea);

		org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(
				jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout
				.setHorizontalGroup(jPanel3Layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								jPanel3Layout
										.createSequentialGroup()
										.add(18, 18, 18)
										.add(
												jPanel3Layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.LEADING)
														.add(jLabel8).add(
																jLabel9).add(
																jLabel10).add(
																jLabel5).add(
																jLabel6).add(
																jLabel7))
										.addPreferredGap(
												org.jdesktop.layout.LayoutStyle.RELATED)
										.add(
												jPanel3Layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.LEADING)
														.add(
																resultClassificationJTextField,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																242,
																Short.MAX_VALUE)
														.add(
																resultNameJTextField,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																242,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
														.add(
																org.jdesktop.layout.GroupLayout.TRAILING,
																attackLevelJTextField,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																242,
																Short.MAX_VALUE)
														.add(
																jScrollPane3,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																242,
																Short.MAX_VALUE)
														.add(
																costAndRarityJTextField,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																242,
																Short.MAX_VALUE)
														.add(
																formAndPreperationJTextField,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																242,
																Short.MAX_VALUE))
										.addContainerGap(
												25,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)));
		jPanel3Layout
				.setVerticalGroup(jPanel3Layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								jPanel3Layout
										.createSequentialGroup()
										.addContainerGap()
										.add(
												jPanel3Layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.BASELINE)
														.add(jLabel5)
														.add(
																resultNameJTextField,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												org.jdesktop.layout.LayoutStyle.UNRELATED)
										.add(
												jPanel3Layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.BASELINE)
														.add(jLabel6)
														.add(
																resultClassificationJTextField,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												org.jdesktop.layout.LayoutStyle.UNRELATED)
										.add(
												jPanel3Layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.BASELINE)
														.add(jLabel7)
														.add(
																attackLevelJTextField,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												org.jdesktop.layout.LayoutStyle.UNRELATED)
										.add(
												jPanel3Layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.BASELINE)
														.add(jLabel8)
														.add(
																formAndPreperationJTextField,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												org.jdesktop.layout.LayoutStyle.RELATED)
										.add(
												jPanel3Layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.TRAILING)
														.add(jLabel9)
														.add(
																costAndRarityJTextField,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												org.jdesktop.layout.LayoutStyle.UNRELATED)
										.add(
												jPanel3Layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.LEADING)
														.add(jLabel10)
														.add(
																jScrollPane3,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
										.addContainerGap(
												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));

		org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(
				jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(
				jPanel2Layout.createSequentialGroup().addContainerGap().add(
						jScrollPane2,
						org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 384,
						org.jdesktop.layout.GroupLayout.PREFERRED_SIZE).add(52,
						52, 52).add(jPanel3,
						org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
						org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
						org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(66, Short.MAX_VALUE)));
		jPanel2Layout
				.setVerticalGroup(jPanel2Layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								jPanel2Layout
										.createSequentialGroup()
										.addContainerGap()
										.add(
												jPanel2Layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.LEADING)
														.add(
																jPanel2Layout
																		.createSequentialGroup()
																		.add(
																				jPanel3,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
																		.addContainerGap())
														.add(
																jPanel2Layout
																		.createSequentialGroup()
																		.add(
																				jScrollPane2,
																				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																				261,
																				Short.MAX_VALUE)
																		.addContainerGap(
																				21,
																				Short.MAX_VALUE)))));

		jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14));
		jLabel4.setText("Search results:");

		org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								layout
										.createSequentialGroup()
										.addContainerGap()
										.add(
												layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.LEADING)
														.add(
																layout
																		.createSequentialGroup()
																		.add(
																				jPanel2,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
																		.addContainerGap())
														.add(
																layout
																		.createParallelGroup(
																				org.jdesktop.layout.GroupLayout.LEADING)
																		.add(
																				layout
																						.createSequentialGroup()
																						.add(
																								jLabel3)
																						.addContainerGap(
																								809,
																								Short.MAX_VALUE))
																		.add(
																				layout
																						.createSequentialGroup()
																						.add(
																								jLabel4)
																						.addContainerGap(
																								810,
																								Short.MAX_VALUE))
																		.add(
																				layout
																						.createSequentialGroup()
																						.add(
																								jPanel1,
																								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
																						.addContainerGap())
																		.add(
																				org.jdesktop.layout.GroupLayout.TRAILING,
																				layout
																						.createSequentialGroup()
																						.add(
																								jLabel1)
																						.add(
																								361,
																								361,
																								361))))));
		layout.setVerticalGroup(layout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(
				layout.createSequentialGroup().addContainerGap().add(jLabel1)
						.add(33, 33, 33).add(jLabel3).addPreferredGap(
								org.jdesktop.layout.LayoutStyle.UNRELATED).add(
								jPanel1,
								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
						.add(29, 29, 29).add(jLabel4).add(18, 18, 18).add(
								jPanel2,
								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(
								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void surpriseSearchJButtonActionPerformed(
			java.awt.event.ActionEvent evt) {
		_myController.surpriseSearchButtonClicked();
	}

	private void searchByNameJButtonActionPerformed(
			java.awt.event.ActionEvent evt) {
		_myController.searchbyNameButtonClicked();
	}

	private void searchByClassificationJButtonActionPerformed(
			java.awt.event.ActionEvent evt) {
		_myController.searchByClassificationButtonClicked();
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new HerbLoreJFrame().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JTextField attackLevelJTextField;
	private javax.swing.JTextField costAndRarityJTextField;
	private javax.swing.JTextArea effectJTextArea;
	private javax.swing.JTextField formAndPreperationJTextField;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JScrollPane jScrollPane3;
	private javax.swing.JTable jTable1;
	private javax.swing.JTextField resultClassificationJTextField;
	private javax.swing.JTextField resultNameJTextField;
	private javax.swing.JButton searchByClassificationJButton;
	private javax.swing.JButton searchByNameJButton;
	private javax.swing.JTextField searchCriteriaJTextField;
	private javax.swing.JTable searchResultsJTable;
	private javax.swing.JButton surpriseSearchJButton;

	// End of variables declaration//GEN-END:variables

	javax.swing.JTextField getSearchCriteriaJTextField() {
		return searchCriteriaJTextField;
	}

	javax.swing.JTextField getAttackLevelJTextField() {
		return attackLevelJTextField;
	}

	javax.swing.JTextField getCostAndRarityJTextField() {
		return costAndRarityJTextField;
	}

	javax.swing.JTextField getFormAndPreperationJTextField() {
		return formAndPreperationJTextField;
	}

	javax.swing.JTextField getResultClassificationJTextField() {
		return resultClassificationJTextField;
	}

	javax.swing.JTextField getResultNameJTextField() {
		return resultNameJTextField;
	}

	javax.swing.JTextArea getEffectJTextArea() {
		return effectJTextArea;
	}
}