/*
 * ItemListJFrame.java
 *
 * Created on __DATE__, __TIME__
 */

package com.sdk.realm.item.ui;

import com.sdk.realm.character.ui.CharacterListTableDataModel;

/**
 *
 * @author  __USER__
 */
public class ItemListJFrame extends javax.swing.JFrame {

	private ItemListFrameController myController;

	/** Creates new form ItemListJFrame */
	public ItemListJFrame() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		itemListJTable = new javax.swing.JTable();
		addItemJButton = new javax.swing.JButton();
		deleteItemJButton = new javax.swing.JButton();
		deleteAllItemsJButton = new javax.swing.JButton();
		editItemJButton = new javax.swing.JButton();

		jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18));
		jLabel1.setText("Item List");

		itemListJTable.setModel(new ItemListTableDataModel());
		jScrollPane1.setViewportView(itemListJTable);

		addItemJButton.setText("Add New Item");
		addItemJButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				addItemJButtonActionPerformed(evt);
			}
		});

		deleteItemJButton.setText("Delete Item");
		deleteItemJButton
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						deleteItemJButtonActionPerformed(evt);
					}
				});

		deleteAllItemsJButton.setText("Delete All Items");
		deleteAllItemsJButton
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						deleteAllItemsJButtonActionPerformed(evt);
					}
				});

		editItemJButton.setText("View & Edit Item Details");
		editItemJButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				editItemJButtonActionPerformed(evt);
			}
		});

		org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								layout
										.createSequentialGroup()
										.add(
												layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.LEADING)
														.add(
																layout
																		.createSequentialGroup()
																		.add(
																				27,
																				27,
																				27)
																		.add(
																				addItemJButton,
																				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																				136,
																				Short.MAX_VALUE)
																		.add(
																				18,
																				18,
																				18)
																		.add(
																				editItemJButton,
																				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																				147,
																				Short.MAX_VALUE)
																		.addPreferredGap(
																				org.jdesktop.layout.LayoutStyle.UNRELATED)
																		.add(
																				deleteItemJButton,
																				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																				137,
																				Short.MAX_VALUE)
																		.addPreferredGap(
																				org.jdesktop.layout.LayoutStyle.UNRELATED)
																		.add(
																				deleteAllItemsJButton,
																				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																				136,
																				Short.MAX_VALUE))
														.add(
																org.jdesktop.layout.GroupLayout.TRAILING,
																layout
																		.createSequentialGroup()
																		.addContainerGap(
																				29,
																				Short.MAX_VALUE)
																		.add(
																				jScrollPane1,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																				592,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
										.addContainerGap()).add(
								org.jdesktop.layout.GroupLayout.TRAILING,
								layout.createSequentialGroup().addContainerGap(
										279, Short.MAX_VALUE).add(jLabel1).add(
										272, 272, 272)));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								layout
										.createSequentialGroup()
										.add(6, 6, 6)
										.add(jLabel1)
										.addPreferredGap(
												org.jdesktop.layout.LayoutStyle.UNRELATED)
										.add(
												jScrollPane1,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												228,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
										.add(18, 18, 18)
										.add(
												layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.BASELINE)
														.add(addItemJButton)
														.add(editItemJButton)
														.add(deleteItemJButton)
														.add(
																deleteAllItemsJButton))
										.addContainerGap(17, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void editItemJButtonActionPerformed(java.awt.event.ActionEvent evt) {
		myController.viewAndEditItemDetailsJButtonClicked();
	}

	private void deleteAllItemsJButtonActionPerformed(
			java.awt.event.ActionEvent evt) {
		myController.deleteAllItemsJButtonClicked();
	}

	private void deleteItemJButtonActionPerformed(java.awt.event.ActionEvent evt) {
		myController.deleteItemJButtonClicked();
	}

	private void addItemJButtonActionPerformed(java.awt.event.ActionEvent evt) {
		myController.addItemJButtonClicked();
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new ItemListJFrame().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton addItemJButton;
	private javax.swing.JButton deleteAllItemsJButton;
	private javax.swing.JButton deleteItemJButton;
	private javax.swing.JButton editItemJButton;
	private javax.swing.JTable itemListJTable;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JScrollPane jScrollPane1;

	// End of variables declaration//GEN-END:variables

	javax.swing.JTable getItemListJTable() {
		return itemListJTable;
	}

	ItemListTableDataModel getTableDataModel() {

		return (ItemListTableDataModel) itemListJTable.getModel();
	}

	public void setController(ItemListFrameController aController) {
		myController = aController;
	}

}