/*
 * MovementManeuverJFrame.java
 *
 * Created on __DATE__, __TIME__
 */

package com.sdk.realm.movement.maneuver.ui;

import javax.swing.JComboBox;
import javax.swing.JSpinner;
import javax.swing.JTextArea;

/**
 *
 * @author  __USER__
 */
public class MovementManeuverJFrame extends javax.swing.JFrame {

	private MovementManeuverFrameController myController;

	/** Creates new form MovementManeuverJFrame */
	public MovementManeuverJFrame() {
		initComponents();
	}

	public MovementManeuverJFrame(MovementManeuverFrameController aController) {
		myController = aController;
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jScrollPane1 = new javax.swing.JScrollPane();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		openEndedRollJButton = new javax.swing.JButton();
		jLabel3 = new javax.swing.JLabel();
		rollResultJSpinner = new javax.swing.JSpinner();
		jLabel10 = new javax.swing.JLabel();
		jScrollPane3 = new javax.swing.JScrollPane();
		currentMovementDescriptionJTextArea = new javax.swing.JTextArea();
		getMovementManeuverJButton = new javax.swing.JButton();
		listMovementManeuversJButton = new javax.swing.JButton();
		jLabel4 = new javax.swing.JLabel();
		difficultyJComboBox = new javax.swing.JComboBox();
		jLabel11 = new javax.swing.JLabel();
		jScrollPane2 = new javax.swing.JScrollPane();
		recentMovementsJList = new javax.swing.JList();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18));
		jLabel1.setText("Movement Maneuver Table");

		jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14));
		jLabel2.setText("Roll Result");

		openEndedRollJButton.setText("Open Ended");
		openEndedRollJButton
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						openEndedRollJButtonActionPerformed(evt);
					}
				});

		jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14));
		jLabel3.setText("Roll");

		rollResultJSpinner.setEditor(new javax.swing.JSpinner.NumberEditor(
				rollResultJSpinner, ""));
		rollResultJSpinner
				.addChangeListener(new javax.swing.event.ChangeListener() {
					public void stateChanged(javax.swing.event.ChangeEvent evt) {
						rollResultJSpinnerStateChanged(evt);
					}
				});

		jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14));
		jLabel10.setText("Current Movement Maneuver");

		currentMovementDescriptionJTextArea.setColumns(20);
		currentMovementDescriptionJTextArea.setEditable(false);
		currentMovementDescriptionJTextArea.setFont(new java.awt.Font("Tahoma",
				0, 13));
		currentMovementDescriptionJTextArea.setLineWrap(true);
		currentMovementDescriptionJTextArea.setRows(3);
		currentMovementDescriptionJTextArea
				.setText("Generate a roll, pick a type and severity, then click the 'Get Critical' button.");
		jScrollPane3.setViewportView(currentMovementDescriptionJTextArea);

		getMovementManeuverJButton.setText("Get Movement-Maneuver");
		getMovementManeuverJButton
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						getMovementManeuverJButtonActionPerformed(evt);
					}
				});

		listMovementManeuversJButton.setText("List Movement-Maneuvers");
		listMovementManeuversJButton
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						listMovementManeuversJButtonActionPerformed(evt);
					}
				});

		jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14));
		jLabel4.setText("Difficulty");

		difficultyJComboBox.setModel(myController.getDifficultyComboBoxModel());
		difficultyJComboBox
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						difficultyJComboBoxActionPerformed(evt);
					}
				});

		jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14));
		jLabel11.setText("Recent Movement Maneuvers");

		recentMovementsJList.setFont(new java.awt.Font("Tahoma", 0, 13));
		recentMovementsJList.setModel(myController.getRecentMovementsListModel());
		recentMovementsJList
				.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
		recentMovementsJList.setFocusable(false);
		recentMovementsJList.setVisibleRowCount(5);
		jScrollPane2.setViewportView(recentMovementsJList);

		org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								layout
										.createSequentialGroup()
										.add(
												layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.LEADING)
														.add(
																layout
																		.createSequentialGroup()
																		.add(
																				58,
																				58,
																				58)
																		.add(
																				jLabel3))
														.add(
																layout
																		.createSequentialGroup()
																		.add(
																				24,
																				24,
																				24)
																		.add(
																				jLabel11))
														.add(
																layout
																		.createSequentialGroup()
																		.add(
																				20,
																				20,
																				20)
																		.add(
																				layout
																						.createParallelGroup(
																								org.jdesktop.layout.GroupLayout.LEADING)
																						.add(
																								layout
																										.createParallelGroup(
																												org.jdesktop.layout.GroupLayout.TRAILING,
																												false)
																										.add(
																												org.jdesktop.layout.GroupLayout.LEADING,
																												jScrollPane3)
																										.add(
																												org.jdesktop.layout.GroupLayout.LEADING,
																												jScrollPane2,
																												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																												670,
																												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
																						.add(
																								layout
																										.createParallelGroup(
																												org.jdesktop.layout.GroupLayout.TRAILING)
																										.add(
																												layout
																														.createSequentialGroup()
																														.add(
																																jLabel10)
																														.add(
																																485,
																																485,
																																485))
																										.add(
																												org.jdesktop.layout.GroupLayout.LEADING,
																												layout
																														.createSequentialGroup()
																														.addPreferredGap(
																																org.jdesktop.layout.LayoutStyle.RELATED)
																														.add(
																																layout
																																		.createParallelGroup(
																																				org.jdesktop.layout.GroupLayout.TRAILING)
																																		.add(
																																				jLabel2)
																																		.add(
																																				layout
																																						.createSequentialGroup()
																																						.add(
																																								openEndedRollJButton)
																																						.add(
																																								18,
																																								18,
																																								18)
																																						.add(
																																								rollResultJSpinner,
																																								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																																								77,
																																								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
																														.add(
																																layout
																																		.createParallelGroup(
																																				org.jdesktop.layout.GroupLayout.LEADING)
																																		.add(
																																				layout
																																						.createSequentialGroup()
																																						.add(
																																								105,
																																								105,
																																								105)
																																						.add(
																																								jLabel4))
																																		.add(
																																				layout
																																						.createSequentialGroup()
																																						.add(
																																								39,
																																								39,
																																								39)
																																						.add(
																																								layout
																																										.createParallelGroup(
																																												org.jdesktop.layout.GroupLayout.LEADING)
																																										.add(
																																												jLabel1)
																																										.add(
																																												layout
																																														.createSequentialGroup()
																																														.add(
																																																difficultyJComboBox,
																																																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																																																173,
																																																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
																																														.add(
																																																43,
																																																43,
																																																43)
																																														.add(
																																																layout
																																																		.createParallelGroup(
																																																				org.jdesktop.layout.GroupLayout.LEADING,
																																																				false)
																																																		.add(
																																																				getMovementManeuverJButton,
																																																				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																																																				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																																																				Short.MAX_VALUE)
																																																		.add(
																																																				listMovementManeuversJButton,
																																																				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																																																				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																																																				Short.MAX_VALUE))))))
																														.add(
																																58,
																																58,
																																58))))))
										.addContainerGap(30, Short.MAX_VALUE)));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								layout
										.createSequentialGroup()
										.addContainerGap()
										.add(jLabel1)
										.add(26, 26, 26)
										.add(
												layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.BASELINE)
														.add(jLabel3).add(
																jLabel2).add(
																jLabel4))
										.add(
												layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.LEADING)
														.add(
																layout
																		.createSequentialGroup()
																		.add(
																				6,
																				6,
																				6)
																		.add(
																				getMovementManeuverJButton)
																		.addPreferredGap(
																				org.jdesktop.layout.LayoutStyle.UNRELATED)
																		.add(
																				listMovementManeuversJButton))
														.add(
																layout
																		.createSequentialGroup()
																		.add(
																				20,
																				20,
																				20)
																		.add(
																				layout
																						.createParallelGroup(
																								org.jdesktop.layout.GroupLayout.BASELINE)
																						.add(
																								rollResultJSpinner,
																								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
																						.add(
																								difficultyJComboBox,
																								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
																						.add(
																								openEndedRollJButton))))
										.add(36, 36, 36)
										.add(jLabel10)
										.addPreferredGap(
												org.jdesktop.layout.LayoutStyle.RELATED)
										.add(
												jScrollPane3,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												72,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
										.add(18, 18, 18)
										.add(jLabel11)
										.add(18, 18, 18)
										.add(
												jScrollPane2,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
										.addContainerGap(27, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void difficultyJComboBoxActionPerformed(
			java.awt.event.ActionEvent evt) {
		myController.difficultyJComboBoxItemSelected();
	}

	private void listMovementManeuversJButtonActionPerformed(
			java.awt.event.ActionEvent evt) {
		myController.listMovementManeuversButtonClicked();
	}

	private void getMovementManeuverJButtonActionPerformed(
			java.awt.event.ActionEvent evt) {
		myController.getMovementManeuverButtonClicked();
	}

	void rollResultJSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {
		myController.rollResultSpinnerStateChanged();
	}

	private void openEndedRollJButtonActionPerformed(
			java.awt.event.ActionEvent evt) {
		myController.openEndedRollButtonClicked();
	}

	JSpinner getRollResultJSpinner() {
		return rollResultJSpinner;
	}

	JTextArea getCurrentMovementDescriptionJTextArea() {
		return currentMovementDescriptionJTextArea;
	}

	JComboBox getDifficultyJComboBox() {
		return difficultyJComboBox;
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new MovementManeuverJFrame().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JTextArea currentMovementDescriptionJTextArea;
	private javax.swing.JComboBox difficultyJComboBox;
	private javax.swing.JButton getMovementManeuverJButton;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JScrollPane jScrollPane3;
	private javax.swing.JButton listMovementManeuversJButton;
	private javax.swing.JButton openEndedRollJButton;
	private javax.swing.JList recentMovementsJList;
	private javax.swing.JSpinner rollResultJSpinner;
	// End of variables declaration//GEN-END:variables

}