//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.12.27 at 06:29:55 PM CST 
//


package com.sdk.realm.character.persistance;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CharacterLibraryType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CharacterLibraryType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CharacterCollection" type="{http://com.sdk.realm/RealmCharacter-v0.0.0.1}CharacterCollectionType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CharacterLibraryType", propOrder = {
    "characterCollection"
})
public class CharacterLibraryType {

    @XmlElement(name = "CharacterCollection", required = true)
    protected CharacterCollectionType characterCollection;

    /**
     * Gets the value of the characterCollection property.
     * 
     * @return
     *     possible object is
     *     {@link CharacterCollectionType }
     *     
     */
    public CharacterCollectionType getCharacterCollection() {
        return characterCollection;
    }

    /**
     * Sets the value of the characterCollection property.
     * 
     * @param value
     *     allowed object is
     *     {@link CharacterCollectionType }
     *     
     */
    public void setCharacterCollection(CharacterCollectionType value) {
        this.characterCollection = value;
    }

}
