//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.12.27 at 06:29:55 PM CST 
//


package com.sdk.realm.character.persistance;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *         		This is a definition of the severity of the hit. The
 *         		severity increases as the letters progress in the
 *         		alphabet.
 *         	
 * 
 * <p>Java class for CharacterType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CharacterType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PlayerID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ObservationSkill" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="Initiative" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="Level" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="ArmorType" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="DefensiveBonus" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="HasShield" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="HasAdrenalDefense" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="StalkSkill" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="SenseAmbushSkill" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="AlertnessSkill" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="Perception" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="InitiativeModifier" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="DefensiveAttributes" type="{http://com.sdk.realm/RealmCharacter-v0.0.0.1}CharacterDefensiveAttributesType" minOccurs="0"/>
 *         &lt;element name="HitPoints" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="Will" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="WillModifier" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="HitPointsModifier" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CharacterType", propOrder = {
    "id",
    "name",
    "playerID",
    "observationSkill",
    "initiative",
    "level",
    "armorType",
    "defensiveBonus",
    "hasShield",
    "hasAdrenalDefense",
    "stalkSkill",
    "senseAmbushSkill",
    "alertnessSkill",
    "perception",
    "initiativeModifier",
    "defensiveAttributes",
    "hitPoints",
    "will",
    "willModifier",
    "hitPointsModifier"
})
public class CharacterType {

    @XmlElement(name = "ID", required = true)
    protected String id;
    @XmlElement(name = "Name", required = true)
    protected String name;
    @XmlElement(name = "PlayerID", required = true)
    protected String playerID;
    @XmlElement(name = "ObservationSkill")
    protected int observationSkill;
    @XmlElement(name = "Initiative")
    protected int initiative;
    @XmlElement(name = "Level")
    protected int level;
    @XmlElement(name = "ArmorType")
    protected int armorType;
    @XmlElement(name = "DefensiveBonus")
    protected Integer defensiveBonus;
    @XmlElement(name = "HasShield")
    protected boolean hasShield;
    @XmlElement(name = "HasAdrenalDefense")
    protected boolean hasAdrenalDefense;
    @XmlElement(name = "StalkSkill")
    protected int stalkSkill;
    @XmlElement(name = "SenseAmbushSkill")
    protected int senseAmbushSkill;
    @XmlElement(name = "AlertnessSkill")
    protected int alertnessSkill;
    @XmlElement(name = "Perception")
    protected int perception;
    @XmlElement(name = "InitiativeModifier")
    protected Integer initiativeModifier;
    @XmlElement(name = "DefensiveAttributes")
    protected CharacterDefensiveAttributesType defensiveAttributes;
    @XmlElement(name = "HitPoints")
    protected Integer hitPoints;
    @XmlElement(name = "Will")
    protected Integer will;
    @XmlElement(name = "WillModifier")
    protected Integer willModifier;
    @XmlElement(name = "HitPointsModifier")
    protected Integer hitPointsModifier;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the playerID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlayerID() {
        return playerID;
    }

    /**
     * Sets the value of the playerID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlayerID(String value) {
        this.playerID = value;
    }

    /**
     * Gets the value of the observationSkill property.
     * 
     */
    public int getObservationSkill() {
        return observationSkill;
    }

    /**
     * Sets the value of the observationSkill property.
     * 
     */
    public void setObservationSkill(int value) {
        this.observationSkill = value;
    }

    /**
     * Gets the value of the initiative property.
     * 
     */
    public int getInitiative() {
        return initiative;
    }

    /**
     * Sets the value of the initiative property.
     * 
     */
    public void setInitiative(int value) {
        this.initiative = value;
    }

    /**
     * Gets the value of the level property.
     * 
     */
    public int getLevel() {
        return level;
    }

    /**
     * Sets the value of the level property.
     * 
     */
    public void setLevel(int value) {
        this.level = value;
    }

    /**
     * Gets the value of the armorType property.
     * 
     */
    public int getArmorType() {
        return armorType;
    }

    /**
     * Sets the value of the armorType property.
     * 
     */
    public void setArmorType(int value) {
        this.armorType = value;
    }

    /**
     * Gets the value of the defensiveBonus property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getDefensiveBonus() {
        return defensiveBonus;
    }

    /**
     * Sets the value of the defensiveBonus property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setDefensiveBonus(Integer value) {
        this.defensiveBonus = value;
    }

    /**
     * Gets the value of the hasShield property.
     * 
     */
    public boolean isHasShield() {
        return hasShield;
    }

    /**
     * Sets the value of the hasShield property.
     * 
     */
    public void setHasShield(boolean value) {
        this.hasShield = value;
    }

    /**
     * Gets the value of the hasAdrenalDefense property.
     * 
     */
    public boolean isHasAdrenalDefense() {
        return hasAdrenalDefense;
    }

    /**
     * Sets the value of the hasAdrenalDefense property.
     * 
     */
    public void setHasAdrenalDefense(boolean value) {
        this.hasAdrenalDefense = value;
    }

    /**
     * Gets the value of the stalkSkill property.
     * 
     */
    public int getStalkSkill() {
        return stalkSkill;
    }

    /**
     * Sets the value of the stalkSkill property.
     * 
     */
    public void setStalkSkill(int value) {
        this.stalkSkill = value;
    }

    /**
     * Gets the value of the senseAmbushSkill property.
     * 
     */
    public int getSenseAmbushSkill() {
        return senseAmbushSkill;
    }

    /**
     * Sets the value of the senseAmbushSkill property.
     * 
     */
    public void setSenseAmbushSkill(int value) {
        this.senseAmbushSkill = value;
    }

    /**
     * Gets the value of the alertnessSkill property.
     * 
     */
    public int getAlertnessSkill() {
        return alertnessSkill;
    }

    /**
     * Sets the value of the alertnessSkill property.
     * 
     */
    public void setAlertnessSkill(int value) {
        this.alertnessSkill = value;
    }

    /**
     * Gets the value of the perception property.
     * 
     */
    public int getPerception() {
        return perception;
    }

    /**
     * Sets the value of the perception property.
     * 
     */
    public void setPerception(int value) {
        this.perception = value;
    }

    /**
     * Gets the value of the initiativeModifier property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getInitiativeModifier() {
        return initiativeModifier;
    }

    /**
     * Sets the value of the initiativeModifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setInitiativeModifier(Integer value) {
        this.initiativeModifier = value;
    }

    /**
     * Gets the value of the defensiveAttributes property.
     * 
     * @return
     *     possible object is
     *     {@link CharacterDefensiveAttributesType }
     *     
     */
    public CharacterDefensiveAttributesType getDefensiveAttributes() {
        return defensiveAttributes;
    }

    /**
     * Sets the value of the defensiveAttributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link CharacterDefensiveAttributesType }
     *     
     */
    public void setDefensiveAttributes(CharacterDefensiveAttributesType value) {
        this.defensiveAttributes = value;
    }

    /**
     * Gets the value of the hitPoints property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getHitPoints() {
        return hitPoints;
    }

    /**
     * Sets the value of the hitPoints property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setHitPoints(Integer value) {
        this.hitPoints = value;
    }

    /**
     * Gets the value of the will property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getWill() {
        return will;
    }

    /**
     * Sets the value of the will property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setWill(Integer value) {
        this.will = value;
    }

    /**
     * Gets the value of the willModifier property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getWillModifier() {
        return willModifier;
    }

    /**
     * Sets the value of the willModifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setWillModifier(Integer value) {
        this.willModifier = value;
    }

    /**
     * Gets the value of the hitPointsModifier property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getHitPointsModifier() {
        return hitPointsModifier;
    }

    /**
     * Sets the value of the hitPointsModifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setHitPointsModifier(Integer value) {
        this.hitPointsModifier = value;
    }

}
