//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.12.27 at 06:29:55 PM CST 
//


package com.sdk.realm.character.persistance;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.sdk.realm.character.persistance package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _CharacterLibrary_QNAME = new QName("http://com.sdk.realm/RealmCharacter-v0.0.0.1", "CharacterLibrary");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.sdk.realm.character.persistance
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CharacterDefensiveAttributesType }
     * 
     */
    public CharacterDefensiveAttributesType createCharacterDefensiveAttributesType() {
        return new CharacterDefensiveAttributesType();
    }

    /**
     * Create an instance of {@link CharacterLibraryType }
     * 
     */
    public CharacterLibraryType createCharacterLibraryType() {
        return new CharacterLibraryType();
    }

    /**
     * Create an instance of {@link CharacterType }
     * 
     */
    public CharacterType createCharacterType() {
        return new CharacterType();
    }

    /**
     * Create an instance of {@link CharacterCollectionType }
     * 
     */
    public CharacterCollectionType createCharacterCollectionType() {
        return new CharacterCollectionType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CharacterLibraryType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.sdk.realm/RealmCharacter-v0.0.0.1", name = "CharacterLibrary")
    public JAXBElement<CharacterLibraryType> createCharacterLibrary(CharacterLibraryType value) {
        return new JAXBElement<CharacterLibraryType>(_CharacterLibrary_QNAME, CharacterLibraryType.class, null, value);
    }

}
