//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.12.27 at 06:29:55 PM CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://com.sdk.realm/RealmCharacter-v0.0.0.1", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.sdk.realm.character.persistance;
