//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.03.25 at 01:26:22 PM CDT 
//


package com.sdk.realm.criticalhit.persistance;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CriticalHitsLibraryType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CriticalHitsLibraryType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CriticalHitCollection" type="{http://com.sdk.realm/RealmCriticalHitsDefinitionV0.0.0.1}CriticalHitCollectionType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CriticalHitsLibraryType", propOrder = {
    "criticalHitCollection"
})
public class CriticalHitsLibraryType {

    @XmlElement(name = "CriticalHitCollection", required = true)
    protected CriticalHitCollectionType criticalHitCollection;

    /**
     * Gets the value of the criticalHitCollection property.
     * 
     * @return
     *     possible object is
     *     {@link CriticalHitCollectionType }
     *     
     */
    public CriticalHitCollectionType getCriticalHitCollection() {
        return criticalHitCollection;
    }

    /**
     * Sets the value of the criticalHitCollection property.
     * 
     * @param value
     *     allowed object is
     *     {@link CriticalHitCollectionType }
     *     
     */
    public void setCriticalHitCollection(CriticalHitCollectionType value) {
        this.criticalHitCollection = value;
    }

}
