//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.03.25 at 01:26:22 PM CDT 
//


package com.sdk.realm.criticalhit.persistance;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.sdk.realm.criticalhit.data package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _CriticalHitLibrary_QNAME = new QName("http://com.sdk.realm/RealmCriticalHitsDefinitionV0.0.0.1", "MovementManeuverLibrary");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.sdk.realm.criticalhit.data
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DiceRollRangeType }
     * 
     */
    public DiceRollRangeType createDiceRollRangeType() {
        return new DiceRollRangeType();
    }

    /**
     * Create an instance of {@link CriticalHitsLibraryType }
     * 
     */
    public CriticalHitsLibraryType createCriticalHitsLibraryType() {
        return new CriticalHitsLibraryType();
    }

    /**
     * Create an instance of {@link CriticalHitType }
     * 
     */
    public CriticalHitType createCriticalHitType() {
        return new CriticalHitType();
    }

    /**
     * Create an instance of {@link CriticalHitCollectionType }
     * 
     */
    public CriticalHitCollectionType createCriticalHitCollectionType() {
        return new CriticalHitCollectionType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CriticalHitsLibraryType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.sdk.realm/RealmCriticalHitsDefinitionV0.0.0.1", name = "MovementManeuverLibrary")
    public JAXBElement<CriticalHitsLibraryType> createCriticalHitLibrary(CriticalHitsLibraryType value) {
        return new JAXBElement<CriticalHitsLibraryType>(_CriticalHitLibrary_QNAME, CriticalHitsLibraryType.class, null, value);
    }

}
