//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.03.25 at 01:26:22 PM CDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://com.sdk.realm/RealmCriticalHitsDefinitionV0.0.0.1", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.sdk.realm.criticalhit.persistance;
