//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.07.31 at 09:58:31 PM CDT 
//


package com.sdk.realm.combat.persistance;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CharacterCombatRoundStatisticsCollectionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CharacterCombatRoundStatisticsCollectionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CharacterCombatRoundStatistic" type="{http://com.sdk.realm/CombatEncounter.V0.0.0.1}CharacterCombatRoundStatisticsType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CharacterCombatRoundStatisticsCollectionType", propOrder = {
    "characterCombatRoundStatistic"
})
public class CharacterCombatRoundStatisticsCollectionType {

    @XmlElement(name = "CharacterCombatRoundStatistic", namespace = "http://com.sdk.realm/CombatEncounter.V0.0.0.1", required = true)
    protected List<CharacterCombatRoundStatisticsType> characterCombatRoundStatistic;

    /**
     * Gets the value of the characterCombatRoundStatistic property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the characterCombatRoundStatistic property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCharacterCombatRoundStatistic().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CharacterCombatRoundStatisticsType }
     * 
     * 
     */
    public List<CharacterCombatRoundStatisticsType> getCharacterCombatRoundStatistic() {
        if (characterCombatRoundStatistic == null) {
            characterCombatRoundStatistic = new ArrayList<CharacterCombatRoundStatisticsType>();
        }
        return this.characterCombatRoundStatistic;
    }

}
