//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.07.31 at 09:58:31 PM CDT 
//


package com.sdk.realm.combat.persistance;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CharacterCombatRoundStatisticsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CharacterCombatRoundStatisticsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CharacterId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="Initiative" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="TotalHits" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="Bleeding" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="RoundsStillStunned" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="NegativeModifier" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="Regeneration" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="HitsAtStartOfRound" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="HitsTakenDuringRound" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="Alertness" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="Observation" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="CharacterTotalHitPointsAtStartOfRound" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="CriticalHitsSuffered" type="{http://com.sdk.realm/CombatEncounter.V0.0.0.1}CriticalHitReferenceCollectionType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CharacterCombatRoundStatisticsType", propOrder = {
    "characterId",
    "initiative",
    "totalHits",
    "bleeding",
    "roundsStillStunned",
    "negativeModifier",
    "regeneration",
    "hitsAtStartOfRound",
    "hitsTakenDuringRound",
    "alertness",
    "observation",
    "characterTotalHitPointsAtStartOfRound",
    "criticalHitsSuffered"
})
public class CharacterCombatRoundStatisticsType {

    @XmlElement(name = "CharacterId", namespace = "http://com.sdk.realm/CombatEncounter.V0.0.0.1")
    protected int characterId;
    @XmlElement(name = "Initiative", namespace = "http://com.sdk.realm/CombatEncounter.V0.0.0.1")
    protected int initiative;
    @XmlElement(name = "TotalHits", namespace = "http://com.sdk.realm/CombatEncounter.V0.0.0.1")
    protected int totalHits;
    @XmlElement(name = "Bleeding", namespace = "http://com.sdk.realm/CombatEncounter.V0.0.0.1")
    protected int bleeding;
    @XmlElement(name = "RoundsStillStunned", namespace = "http://com.sdk.realm/CombatEncounter.V0.0.0.1")
    protected int roundsStillStunned;
    @XmlElement(name = "NegativeModifier", namespace = "http://com.sdk.realm/CombatEncounter.V0.0.0.1")
    protected int negativeModifier;
    @XmlElement(name = "Regeneration", namespace = "http://com.sdk.realm/CombatEncounter.V0.0.0.1")
    protected int regeneration;
    @XmlElement(name = "HitsAtStartOfRound", namespace = "http://com.sdk.realm/CombatEncounter.V0.0.0.1")
    protected int hitsAtStartOfRound;
    @XmlElement(name = "HitsTakenDuringRound", namespace = "http://com.sdk.realm/CombatEncounter.V0.0.0.1")
    protected int hitsTakenDuringRound;
    @XmlElement(name = "Alertness", namespace = "http://com.sdk.realm/CombatEncounter.V0.0.0.1")
    protected int alertness;
    @XmlElement(name = "Observation", namespace = "http://com.sdk.realm/CombatEncounter.V0.0.0.1")
    protected int observation;
    @XmlElement(name = "CharacterTotalHitPointsAtStartOfRound", namespace = "http://com.sdk.realm/CombatEncounter.V0.0.0.1")
    protected int characterTotalHitPointsAtStartOfRound;
    @XmlElement(name = "CriticalHitsSuffered", namespace = "http://com.sdk.realm/CombatEncounter.V0.0.0.1", required = true)
    protected CriticalHitReferenceCollectionType criticalHitsSuffered;

    /**
     * Gets the value of the characterId property.
     * 
     */
    public int getCharacterId() {
        return characterId;
    }

    /**
     * Sets the value of the characterId property.
     * 
     */
    public void setCharacterId(int value) {
        this.characterId = value;
    }

    /**
     * Gets the value of the initiative property.
     * 
     */
    public int getInitiative() {
        return initiative;
    }

    /**
     * Sets the value of the initiative property.
     * 
     */
    public void setInitiative(int value) {
        this.initiative = value;
    }

    /**
     * Gets the value of the totalHits property.
     * 
     */
    public int getTotalHits() {
        return totalHits;
    }

    /**
     * Sets the value of the totalHits property.
     * 
     */
    public void setTotalHits(int value) {
        this.totalHits = value;
    }

    /**
     * Gets the value of the bleeding property.
     * 
     */
    public int getBleeding() {
        return bleeding;
    }

    /**
     * Sets the value of the bleeding property.
     * 
     */
    public void setBleeding(int value) {
        this.bleeding = value;
    }

    /**
     * Gets the value of the roundsStillStunned property.
     * 
     */
    public int getRoundsStillStunned() {
        return roundsStillStunned;
    }

    /**
     * Sets the value of the roundsStillStunned property.
     * 
     */
    public void setRoundsStillStunned(int value) {
        this.roundsStillStunned = value;
    }

    /**
     * Gets the value of the negativeModifier property.
     * 
     */
    public int getNegativeModifier() {
        return negativeModifier;
    }

    /**
     * Sets the value of the negativeModifier property.
     * 
     */
    public void setNegativeModifier(int value) {
        this.negativeModifier = value;
    }

    /**
     * Gets the value of the regeneration property.
     * 
     */
    public int getRegeneration() {
        return regeneration;
    }

    /**
     * Sets the value of the regeneration property.
     * 
     */
    public void setRegeneration(int value) {
        this.regeneration = value;
    }

    /**
     * Gets the value of the hitsAtStartOfRound property.
     * 
     */
    public int getHitsAtStartOfRound() {
        return hitsAtStartOfRound;
    }

    /**
     * Sets the value of the hitsAtStartOfRound property.
     * 
     */
    public void setHitsAtStartOfRound(int value) {
        this.hitsAtStartOfRound = value;
    }

    /**
     * Gets the value of the hitsTakenDuringRound property.
     * 
     */
    public int getHitsTakenDuringRound() {
        return hitsTakenDuringRound;
    }

    /**
     * Sets the value of the hitsTakenDuringRound property.
     * 
     */
    public void setHitsTakenDuringRound(int value) {
        this.hitsTakenDuringRound = value;
    }

    /**
     * Gets the value of the alertness property.
     * 
     */
    public int getAlertness() {
        return alertness;
    }

    /**
     * Sets the value of the alertness property.
     * 
     */
    public void setAlertness(int value) {
        this.alertness = value;
    }

    /**
     * Gets the value of the observation property.
     * 
     */
    public int getObservation() {
        return observation;
    }

    /**
     * Sets the value of the observation property.
     * 
     */
    public void setObservation(int value) {
        this.observation = value;
    }

    /**
     * Gets the value of the characterTotalHitPointsAtStartOfRound property.
     * 
     */
    public int getCharacterTotalHitPointsAtStartOfRound() {
        return characterTotalHitPointsAtStartOfRound;
    }

    /**
     * Sets the value of the characterTotalHitPointsAtStartOfRound property.
     * 
     */
    public void setCharacterTotalHitPointsAtStartOfRound(int value) {
        this.characterTotalHitPointsAtStartOfRound = value;
    }

    /**
     * Gets the value of the criticalHitsSuffered property.
     * 
     * @return
     *     possible object is
     *     {@link CriticalHitReferenceCollectionType }
     *     
     */
    public CriticalHitReferenceCollectionType getCriticalHitsSuffered() {
        return criticalHitsSuffered;
    }

    /**
     * Sets the value of the criticalHitsSuffered property.
     * 
     * @param value
     *     allowed object is
     *     {@link CriticalHitReferenceCollectionType }
     *     
     */
    public void setCriticalHitsSuffered(CriticalHitReferenceCollectionType value) {
        this.criticalHitsSuffered = value;
    }

}
