//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.07.31 at 09:58:31 PM CDT 
//


package com.sdk.realm.combat.persistance;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CriticalHitReferenceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CriticalHitReferenceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Severity" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="RangeMinimum" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="RangeMaximum" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CriticalHitReferenceType", propOrder = {
    "type",
    "severity",
    "rangeMinimum",
    "rangeMaximum"
})
public class CriticalHitReferenceType {

    @XmlElement(name = "Type", namespace = "http://com.sdk.realm/CombatEncounter.V0.0.0.1", required = true)
    protected String type;
    @XmlElement(name = "Severity", namespace = "http://com.sdk.realm/CombatEncounter.V0.0.0.1", required = true)
    protected String severity;
    @XmlElement(name = "RangeMinimum", namespace = "http://com.sdk.realm/CombatEncounter.V0.0.0.1")
    protected int rangeMinimum;
    @XmlElement(name = "RangeMaximum", namespace = "http://com.sdk.realm/CombatEncounter.V0.0.0.1")
    protected int rangeMaximum;

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the severity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSeverity() {
        return severity;
    }

    /**
     * Sets the value of the severity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSeverity(String value) {
        this.severity = value;
    }

    /**
     * Gets the value of the rangeMinimum property.
     * 
     */
    public int getRangeMinimum() {
        return rangeMinimum;
    }

    /**
     * Sets the value of the rangeMinimum property.
     * 
     */
    public void setRangeMinimum(int value) {
        this.rangeMinimum = value;
    }

    /**
     * Gets the value of the rangeMaximum property.
     * 
     */
    public int getRangeMaximum() {
        return rangeMaximum;
    }

    /**
     * Sets the value of the rangeMaximum property.
     * 
     */
    public void setRangeMaximum(int value) {
        this.rangeMaximum = value;
    }

}
