//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.07.31 at 09:58:31 PM CDT 
//


package com.sdk.realm.combat.persistance;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.sdk.realm.combat.persistance package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _CombatEncounter_QNAME = new QName("http://com.sdk.realm/CombatEncounter.V0.0.0.1", "CombatEncounter");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.sdk.realm.combat.persistance
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RoundCollectionType }
     * 
     */
    public RoundCollectionType createRoundCollectionType() {
        return new RoundCollectionType();
    }

    /**
     * Create an instance of {@link CriticalHitReferenceCollectionType }
     * 
     */
    public CriticalHitReferenceCollectionType createCriticalHitReferenceCollectionType() {
        return new CriticalHitReferenceCollectionType();
    }

    /**
     * Create an instance of {@link CriticalHitReferenceType }
     * 
     */
    public CriticalHitReferenceType createCriticalHitReferenceType() {
        return new CriticalHitReferenceType();
    }

    /**
     * Create an instance of {@link CharacterCombatRoundStatisticsType }
     * 
     */
    public CharacterCombatRoundStatisticsType createCharacterCombatRoundStatisticsType() {
        return new CharacterCombatRoundStatisticsType();
    }

    /**
     * Create an instance of {@link RoundType }
     * 
     */
    public RoundType createRoundType() {
        return new RoundType();
    }

    /**
     * Create an instance of {@link CombatEncounterType }
     * 
     */
    public CombatEncounterType createCombatEncounterType() {
        return new CombatEncounterType();
    }

    /**
     * Create an instance of {@link CharacterCombatRoundStatisticsCollectionType }
     * 
     */
    public CharacterCombatRoundStatisticsCollectionType createCharacterCombatRoundStatisticsCollectionType() {
        return new CharacterCombatRoundStatisticsCollectionType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CombatEncounterType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.sdk.realm/CombatEncounter.V0.0.0.1", name = "CombatEncounter")
    public JAXBElement<CombatEncounterType> createCombatEncounter(CombatEncounterType value) {
        return new JAXBElement<CombatEncounterType>(_CombatEncounter_QNAME, CombatEncounterType.class, null, value);
    }

}
