//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.07.31 at 09:58:31 PM CDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://com.sdk.realm/CombatEncounter.V0.0.0.1")
package com.sdk.realm.combat.persistance;
