//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.07.31 at 09:58:31 PM CDT 
//


package com.sdk.realm.combat.persistance;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for RoundType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RoundType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RoundNumber" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="Status">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *               &lt;enumeration value="Open"/>
 *               &lt;enumeration value="Closed"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="CharacterCombatRoundStatistics" type="{http://com.sdk.realm/CombatEncounter.V0.0.0.1}CharacterCombatRoundStatisticsCollectionType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RoundType", propOrder = {
    "roundNumber",
    "status",
    "characterCombatRoundStatistics"
})
public class RoundType {

    @XmlElement(name = "RoundNumber", namespace = "http://com.sdk.realm/CombatEncounter.V0.0.0.1")
    protected int roundNumber;
    @XmlElement(name = "Status", namespace = "http://com.sdk.realm/CombatEncounter.V0.0.0.1", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String status;
    @XmlElement(name = "CharacterCombatRoundStatistics", namespace = "http://com.sdk.realm/CombatEncounter.V0.0.0.1", required = true)
    protected CharacterCombatRoundStatisticsCollectionType characterCombatRoundStatistics;

    /**
     * Gets the value of the roundNumber property.
     * 
     */
    public int getRoundNumber() {
        return roundNumber;
    }

    /**
     * Sets the value of the roundNumber property.
     * 
     */
    public void setRoundNumber(int value) {
        this.roundNumber = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the characterCombatRoundStatistics property.
     * 
     * @return
     *     possible object is
     *     {@link CharacterCombatRoundStatisticsCollectionType }
     *     
     */
    public CharacterCombatRoundStatisticsCollectionType getCharacterCombatRoundStatistics() {
        return characterCombatRoundStatistics;
    }

    /**
     * Sets the value of the characterCombatRoundStatistics property.
     * 
     * @param value
     *     allowed object is
     *     {@link CharacterCombatRoundStatisticsCollectionType }
     *     
     */
    public void setCharacterCombatRoundStatistics(CharacterCombatRoundStatisticsCollectionType value) {
        this.characterCombatRoundStatistics = value;
    }

}
