/*
 * ResistanceTableFrame.java
 *
 * Created on __DATE__, __TIME__
 */

package com.sdk.realm.resistancetable.ui;

/**
 *
 * @author  __USER__
 */
public class ResistanceTableFrame extends javax.swing.JFrame {

	ResistanceTableFrameController _myController = null;

	/** Creates new form ResistanceTableFrame */
	public ResistanceTableFrame() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jScrollPane1 = new javax.swing.JScrollPane();
		jTable1 = new javax.swing.JTable();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		attackJSpinner = new javax.swing.JSpinner();
		jLabel3 = new javax.swing.JLabel();
		targetJSpinner = new javax.swing.JSpinner();
		resistanceRollJTextField = new javax.swing.JTextField();
		jLabel5 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		saveResistanceRollButton = new javax.swing.JButton();
		jLabel6 = new javax.swing.JLabel();
		jScrollPane2 = new javax.swing.JScrollPane();
		recentActivityJTable = new javax.swing.JTable();

		jTable1.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null } }, new String[] { "Title 1",
						"Title 2", "Title 3", "Title 4" }));
		jScrollPane1.setViewportView(jTable1);

		setResizable(false);

		jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18));
		jLabel1.setText("Resistance Table");

		jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14));
		jLabel2.setText("Attacker Level");

		attackJSpinner.setFont(new java.awt.Font("Courier", 0, 14));
		attackJSpinner.setModel(new javax.swing.SpinnerNumberModel(Integer
				.valueOf(100), Integer.valueOf(0), null, Integer.valueOf(1)));
		attackJSpinner
				.addChangeListener(new javax.swing.event.ChangeListener() {
					public void stateChanged(javax.swing.event.ChangeEvent evt) {
						attackJSpinnerStateChanged(evt);
					}
				});

		jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14));
		jLabel3.setText("Target Level");

		targetJSpinner.setFont(new java.awt.Font("Courier", 0, 14));
		targetJSpinner.setModel(new javax.swing.SpinnerNumberModel(Integer
				.valueOf(100), Integer.valueOf(0), null, Integer.valueOf(1)));
		targetJSpinner
				.addChangeListener(new javax.swing.event.ChangeListener() {
					public void stateChanged(javax.swing.event.ChangeEvent evt) {
						targetJSpinnerStateChanged(evt);
					}
				});

		resistanceRollJTextField.setEditable(false);
		resistanceRollJTextField.setFont(new java.awt.Font("Tahoma", 0, 14));
		resistanceRollJTextField.setText("50");

		jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14));
		jLabel5.setText("Target Resists At");

		jLabel4.setText("==>");

		saveResistanceRollButton.setText("Save");
		saveResistanceRollButton
				.addMouseListener(new java.awt.event.MouseAdapter() {
					public void mouseClicked(java.awt.event.MouseEvent evt) {
						saveResistanceRollButtonMouseClicked(evt);
					}
				});

		jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14));
		jLabel6.setText("Recent Activity");

		recentActivityJTable.setFont(new java.awt.Font("Tahoma", 0, 14));
		recentActivityJTable
				.setModel(new ResistanceRecentActivityTableDataModel());
		jScrollPane2.setViewportView(recentActivityJTable);

		org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								layout
										.createSequentialGroup()
										.add(
												layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.LEADING)
														.add(
																layout
																		.createSequentialGroup()
																		.addContainerGap()
																		.add(
																				layout
																						.createParallelGroup(
																								org.jdesktop.layout.GroupLayout.LEADING)
																						.add(
																								layout
																										.createSequentialGroup()
																										.add(
																												attackJSpinner,
																												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																												84,
																												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
																										.add(
																												20,
																												20,
																												20)
																										.add(
																												targetJSpinner,
																												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																												71,
																												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
																										.addPreferredGap(
																												org.jdesktop.layout.LayoutStyle.UNRELATED)
																										.add(
																												jLabel4))
																						.add(
																								layout
																										.createSequentialGroup()
																										.add(
																												jLabel2,
																												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																												102,
																												Short.MAX_VALUE)
																										.addPreferredGap(
																												org.jdesktop.layout.LayoutStyle.RELATED)
																										.add(
																												jLabel3)
																										.add(
																												26,
																												26,
																												26)))
																		.add(
																				14,
																				14,
																				14)
																		.add(
																				layout
																						.createParallelGroup(
																								org.jdesktop.layout.GroupLayout.LEADING)
																						.add(
																								layout
																										.createSequentialGroup()
																										.add(
																												resistanceRollJTextField,
																												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																												84,
																												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
																										.add(
																												39,
																												39,
																												39)
																										.add(
																												saveResistanceRollButton))
																						.add(
																								jLabel5,
																								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																								212,
																								Short.MAX_VALUE)))
														.add(
																layout
																		.createSequentialGroup()
																		.add(
																				124,
																				124,
																				124)
																		.add(
																				jLabel1))
														.add(
																layout
																		.createSequentialGroup()
																		.addContainerGap()
																		.add(
																				jScrollPane2,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																				430,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
										.addContainerGap())
						.add(
								org.jdesktop.layout.GroupLayout.TRAILING,
								layout
										.createSequentialGroup()
										.addContainerGap(175, Short.MAX_VALUE)
										.add(
												jLabel6,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												118,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
										.add(162, 162, 162)));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								layout
										.createSequentialGroup()
										.addContainerGap()
										.add(jLabel1)
										.add(11, 11, 11)
										.add(
												layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.BASELINE)
														.add(
																jLabel2,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																31,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
														.add(jLabel3).add(
																jLabel5))
										.addPreferredGap(
												org.jdesktop.layout.LayoutStyle.RELATED)
										.add(
												layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.BASELINE)
														.add(attackJSpinner)
														.add(
																targetJSpinner,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
														.add(jLabel4)
														.add(
																resistanceRollJTextField,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
														.add(
																saveResistanceRollButton))
										.add(27, 27, 27)
										.add(jLabel6)
										.addPreferredGap(
												org.jdesktop.layout.LayoutStyle.RELATED)
										.add(
												jScrollPane2,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												179,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
										.add(22, 22, 22)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void targetJSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {
		_myController.targetSpinnerValueChanged();
	}

	private void attackJSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {
		_myController.attackSpinnerValueChanged();
	}

	public void saveResistanceRollButtonMouseClicked(
			java.awt.event.MouseEvent evt) {
		_myController.saveResistanceRollButtonClicked();
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new ResistanceTableFrame().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JSpinner attackJSpinner;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JTable jTable1;
	private javax.swing.JTable recentActivityJTable;
	private javax.swing.JTextField resistanceRollJTextField;
	private javax.swing.JButton saveResistanceRollButton;
	private javax.swing.JSpinner targetJSpinner;

	// End of variables declaration//GEN-END:variables

	javax.swing.JTable getRecentActivityJTable() {
		return recentActivityJTable;
	}

	javax.swing.JSpinner getAttackJSpinner() {
		return attackJSpinner;
	}

	javax.swing.JSpinner getTargetJSpinner() {
		return targetJSpinner;
	}

	javax.swing.JTextField getResistanceRollJTextField() {
		return resistanceRollJTextField;
	}

	public void setController(ResistanceTableFrameController aController) {
		_myController = aController;
	}
}