//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.05.23 at 03:00:01 PM CDT 
//


package com.sdk.realm.player.persistance;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.sdk.realm.player.persistance package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _PlayerWarehouse_QNAME = new QName("http://com.sdk.realm/PlayersV0.0.0.1", "PlayerWarehouse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.sdk.realm.player.persistance
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PlayerWarehouseType }
     * 
     */
    public PlayerWarehouseType createPlayerWarehouseType() {
        return new PlayerWarehouseType();
    }

    /**
     * Create an instance of {@link PlayerType }
     * 
     */
    public PlayerType createPlayerType() {
        return new PlayerType();
    }

    /**
     * Create an instance of {@link PlayerCollectionType }
     * 
     */
    public PlayerCollectionType createPlayerCollectionType() {
        return new PlayerCollectionType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PlayerWarehouseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.sdk.realm/PlayersV0.0.0.1", name = "PlayerWarehouse")
    public JAXBElement<PlayerWarehouseType> createPlayerWarehouse(PlayerWarehouseType value) {
        return new JAXBElement<PlayerWarehouseType>(_PlayerWarehouse_QNAME, PlayerWarehouseType.class, null, value);
    }

}
