//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.05.23 at 03:00:01 PM CDT 
//


package com.sdk.realm.player.persistance;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PlayerWarehouseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PlayerWarehouseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PlayerCollection" type="{http://com.sdk.realm/PlayersV0.0.0.1}PlayerCollectionType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PlayerWarehouseType", propOrder = {
    "playerCollection"
})
public class PlayerWarehouseType {

    @XmlElement(name = "PlayerCollection", required = true)
    protected PlayerCollectionType playerCollection;

    /**
     * Gets the value of the playerCollection property.
     * 
     * @return
     *     possible object is
     *     {@link PlayerCollectionType }
     *     
     */
    public PlayerCollectionType getPlayerCollection() {
        return playerCollection;
    }

    /**
     * Sets the value of the playerCollection property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlayerCollectionType }
     *     
     */
    public void setPlayerCollection(PlayerCollectionType value) {
        this.playerCollection = value;
    }

}
