/*
 * CharacterListJFrame.java
 *
 * Created on __DATE__, __TIME__
 */

package com.sdk.realm.character.ui;

/**
 *
 * @author  __USER__
 */
public class CharacterListJFrame extends javax.swing.JFrame {

	private CharacterListFrameController _myController = null;

	/** Creates new form CharacterListJFrame */
	public CharacterListJFrame() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		characterListJTable = new javax.swing.JTable();
		addCharacterJButton = new javax.swing.JButton();
		viewAndEditCharacterDetailsJButton = new javax.swing.JButton();
		deleteCharacterJButton = new javax.swing.JButton();
		deleteAllCharactersJButton = new javax.swing.JButton();
		viewAndEditCharacterDefensiveAttributesjButton = new javax.swing.JButton();

		jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18));
		jLabel1.setText("Character List");

		characterListJTable.setModel(new CharacterListTableDataModel());
		jScrollPane1.setViewportView(characterListJTable);

		addCharacterJButton.setText("Add New Character");
		addCharacterJButton
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						addCharacterJButtonActionPerformed(evt);
					}
				});

		viewAndEditCharacterDetailsJButton
				.setText("View & Edit Character Details");
		viewAndEditCharacterDetailsJButton
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						viewAndEditCharacterDetailsJButtonActionPerformed(evt);
					}
				});

		deleteCharacterJButton.setText("Delete Character");
		deleteCharacterJButton
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						deleteCharacterJButtonActionPerformed(evt);
					}
				});

		deleteAllCharactersJButton.setText("Delete All Characters");
		deleteAllCharactersJButton
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						deleteAllCharactersJButtonActionPerformed(evt);
					}
				});

		viewAndEditCharacterDefensiveAttributesjButton
				.setText("View & Edit Defensive Attributes List");
		viewAndEditCharacterDefensiveAttributesjButton
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						viewAndEditCharacterDefensiveAttributesjButtonActionPerformed(evt);
					}
				});

		org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								layout
										.createSequentialGroup()
										.add(
												layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.LEADING)
														.add(
																layout
																		.createSequentialGroup()
																		.addContainerGap()
																		.add(
																				addCharacterJButton)
																		.addPreferredGap(
																				org.jdesktop.layout.LayoutStyle.UNRELATED)
																		.add(
																				viewAndEditCharacterDetailsJButton)
																		.add(
																				14,
																				14,
																				14)
																		.add(
																				viewAndEditCharacterDefensiveAttributesjButton)
																		.add(
																				14,
																				14,
																				14)
																		.add(
																				deleteCharacterJButton)
																		.addPreferredGap(
																				org.jdesktop.layout.LayoutStyle.UNRELATED)
																		.add(
																				deleteAllCharactersJButton))
														.add(
																layout
																		.createSequentialGroup()
																		.addContainerGap()
																		.add(
																				jScrollPane1,
																				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																				833,
																				Short.MAX_VALUE))
														.add(
																layout
																		.createSequentialGroup()
																		.add(
																				328,
																				328,
																				328)
																		.add(
																				jLabel1)))
										.addContainerGap()));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								layout
										.createSequentialGroup()
										.addContainerGap()
										.add(jLabel1)
										.add(11, 11, 11)
										.add(
												jScrollPane1,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												275,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
										.add(18, 18, 18)
										.add(
												layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.BASELINE)
														.add(
																addCharacterJButton)
														.add(
																deleteAllCharactersJButton)
														.add(
																viewAndEditCharacterDefensiveAttributesjButton)
														.add(
																deleteCharacterJButton)
														.add(
																viewAndEditCharacterDetailsJButton))
										.addContainerGap(23, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void viewAndEditCharacterDefensiveAttributesjButtonActionPerformed(
			java.awt.event.ActionEvent evt) {
		_myController
				.viewAndEditCharacterDefensiveBonusAttributesJButtonClicked();
	}

	private void deleteAllCharactersJButtonActionPerformed(
			java.awt.event.ActionEvent evt) {
		_myController.deleteAllCharactersJButtonClicked();
	}

	private void deleteCharacterJButtonActionPerformed(
			java.awt.event.ActionEvent evt) {
		_myController.deleteCharacterJButtonClicked();
	}

	private void addCharacterJButtonActionPerformed(
			java.awt.event.ActionEvent evt) {
		_myController.addCharacterJButtonClicked();
	}

	void viewAndEditCharacterDetailsJButtonActionPerformed(
			java.awt.event.ActionEvent evt) {
		_myController.viewAndEditCharacterDetailsJButtonClicked();

	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new CharacterListJFrame().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton addCharacterJButton;
	private javax.swing.JTable characterListJTable;
	private javax.swing.JButton deleteAllCharactersJButton;
	private javax.swing.JButton deleteCharacterJButton;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JButton viewAndEditCharacterDefensiveAttributesjButton;
	private javax.swing.JButton viewAndEditCharacterDetailsJButton;

	// End of variables declaration//GEN-END:variables

	CharacterListTableDataModel getTableDataModel() {

		return (CharacterListTableDataModel) characterListJTable.getModel();
	}

	public void setController(CharacterListFrameController aController) {
		_myController = aController;
		getTableDataModel().setMyFrameController(aController);
	}

	javax.swing.JTable getCharacterListJTable() {
		return characterListJTable;
	}
}