/*
 * CharacterDefensiveAttributesListJFrame.java
 *
 * Created on __DATE__, __TIME__
 */

package com.sdk.realm.character.ui;

/**
 *
 * @author  __USER__
 */
public class CharacterDefensiveAttributesListJFrame extends javax.swing.JFrame {

	private CharacterDefensiveAttributesListFrameController _myController = null;

	/** Creates new form CharacterDefensiveAttributesListJFrame */
	public CharacterDefensiveAttributesListJFrame() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		characterDefensiveAttributesListJTable = new javax.swing.JTable();
		viewAndEditCharacterDefensiveAttributeDetailsJButton = new javax.swing.JButton();

		jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18));
		jLabel1.setText("Character Defensive Attributes List");

		characterDefensiveAttributesListJTable
				.setModel(new CharacterDefensiveAttributesListTableDataModel());
		jScrollPane1.setViewportView(characterDefensiveAttributesListJTable);

		viewAndEditCharacterDefensiveAttributeDetailsJButton
				.setText("View & Edit Character Defensive Attribute Details");
		viewAndEditCharacterDefensiveAttributeDetailsJButton
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						viewAndEditCharacterDefensiveAttributeDetailsJButtonActionPerformed(evt);
					}
				});

		org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								layout
										.createSequentialGroup()
										.add(
												layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.LEADING)
														.add(
																layout
																		.createSequentialGroup()
																		.add(
																				307,
																				307,
																				307)
																		.add(
																				jLabel1))
														.add(
																layout
																		.createSequentialGroup()
																		.add(
																				26,
																				26,
																				26)
																		.add(
																				jScrollPane1,
																				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																				941,
																				Short.MAX_VALUE))
														.add(
																layout
																		.createSequentialGroup()
																		.add(
																				302,
																				302,
																				302)
																		.add(
																				viewAndEditCharacterDefensiveAttributeDetailsJButton)))
										.addContainerGap()));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								layout
										.createSequentialGroup()
										.add(4, 4, 4)
										.add(jLabel1)
										.add(18, 18, 18)
										.add(
												jScrollPane1,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												272,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												org.jdesktop.layout.LayoutStyle.RELATED,
												27, Short.MAX_VALUE)
										.add(
												viewAndEditCharacterDefensiveAttributeDetailsJButton)
										.add(25, 25, 25)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void viewAndEditCharacterDefensiveAttributeDetailsJButtonActionPerformed(
			java.awt.event.ActionEvent evt) {
		_myController.viewAndEditCharacterDefensiveAttributesDetailsJButtonClicked();
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new CharacterDefensiveAttributesListJFrame().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JTable characterDefensiveAttributesListJTable;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JButton viewAndEditCharacterDefensiveAttributeDetailsJButton;

	// End of variables declaration//GEN-END:variables

	CharacterDefensiveAttributesListTableDataModel getTableDataModel() {

		return (CharacterDefensiveAttributesListTableDataModel) characterDefensiveAttributesListJTable
				.getModel();
	}
	
	public void setController(
			CharacterDefensiveAttributesListFrameController aController) {
		_myController = aController;
		getTableDataModel().setMyFrameController(aController);
	}

	javax.swing.JTable getCharacterDefensiveAttributesListJTable() {
		return characterDefensiveAttributesListJTable;
	}
}