//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.08.14 at 11:17:57 PM CDT 
//


package com.sdk.realm.movement.maneuver.persistance;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;


/**
 * <p>Java class for MovementManeuverDifficultyType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="MovementManeuverDifficultyType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="routine"/>
 *     &lt;enumeration value="easy"/>
 *     &lt;enumeration value="light"/>
 *     &lt;enumeration value="medium"/>
 *     &lt;enumeration value="hard"/>
 *     &lt;enumeration value="veryHard"/>
 *     &lt;enumeration value="extremelyHard"/>
 *     &lt;enumeration value="sheerFolly"/>
 *     &lt;enumeration value="absurd"/>
 *     &lt;enumeration value="trivial"/>
 *     &lt;enumeration value="insane"/>
 *     &lt;enumeration value="phenomenal"/>
 *     &lt;enumeration value="virtuallyImpossible"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlEnum
public enum MovementManeuverDifficultyType {

    @XmlEnumValue("routine")
    ROUTINE("routine"),
    @XmlEnumValue("easy")
    EASY("easy"),
    @XmlEnumValue("light")
    LIGHT("light"),
    @XmlEnumValue("medium")
    MEDIUM("medium"),
    @XmlEnumValue("hard")
    HARD("hard"),
    @XmlEnumValue("veryHard")
    VERY_HARD("veryHard"),
    @XmlEnumValue("extremelyHard")
    EXTREMELY_HARD("extremelyHard"),
    @XmlEnumValue("sheerFolly")
    SHEER_FOLLY("sheerFolly"),
    @XmlEnumValue("absurd")
    ABSURD("absurd"),
    @XmlEnumValue("trivial")
    TRIVIAL("trivial"),
    @XmlEnumValue("insane")
    INSANE("insane"),
    @XmlEnumValue("phenomenal")
    PHENOMENAL("phenomenal"),
    @XmlEnumValue("virtuallyImpossible")
    VIRTUALLY_IMPOSSIBLE("virtuallyImpossible");
    private final String value;

    MovementManeuverDifficultyType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static MovementManeuverDifficultyType fromValue(String v) {
        for (MovementManeuverDifficultyType c: MovementManeuverDifficultyType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
