//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.08.14 at 11:17:57 PM CDT 
//


package com.sdk.realm.movement.maneuver.persistance;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MovementManeuverCollectionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MovementManeuverCollectionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MovementManeuver" type="{http://com.sdk.realm/RealmMovementManeuverDefinitionV0.0.0.1}MovementManeuverType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MovementManeuverCollectionType", propOrder = {
    "movementManeuvers"
})
public class MovementManeuverCollectionType {

    @XmlElement(name = "MovementManeuver")
    protected List<MovementManeuverType> movementManeuvers;

    /**
     * Gets the value of the movementManeuvers property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the movementManeuvers property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMovementManeuvers().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MovementManeuverType }
     * 
     * 
     */
    public List<MovementManeuverType> getMovementManeuvers() {
        if (movementManeuvers == null) {
            movementManeuvers = new ArrayList<MovementManeuverType>();
        }
        return this.movementManeuvers;
    }

}
