//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.08.14 at 11:17:57 PM CDT 
//


package com.sdk.realm.movement.maneuver.persistance;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.sdk.realm.movement.maneuver.persistance package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.sdk.realm.movement.maneuver.persistance
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DiceRollRangeType }
     * 
     */
    public DiceRollRangeType createDiceRollRangeType() {
        return new DiceRollRangeType();
    }

    /**
     * Create an instance of {@link MovementManeuverType }
     * 
     */
    public MovementManeuverType createMovementManeuverType() {
        return new MovementManeuverType();
    }

    /**
     * Create an instance of {@link MovementManeuverCollectionType }
     * 
     */
    public MovementManeuverCollectionType createMovementManeuverCollectionType() {
        return new MovementManeuverCollectionType();
    }

    /**
     * Create an instance of {@link MovementManeuverLibrary }
     * 
     */
    public MovementManeuverLibrary createMovementManeuverLibrary() {
        return new MovementManeuverLibrary();
    }

}
