//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.08.14 at 11:17:57 PM CDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://com.sdk.realm/RealmMovementManeuverDefinitionV0.0.0.1", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.sdk.realm.movement.maneuver.persistance;
