//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.06.07 at 09:50:47 PM CDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://com.sdk.realm/RealmWillContestConsequencesDefinitionV0.0.0.1", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.sdk.realm.willcontest.consequence.persistance;
