//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.06.07 at 09:50:47 PM CDT 
//


package com.sdk.realm.willcontest.consequence.persistance;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *         		This is a definition of the severity of the hit. The
 *         		severity increases as the letters progress in the
 *         		alphabet.
 *         	
 * 
 * <p>Java class for WillContestConsequenceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WillContestConsequenceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PermanentBonus" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="RollValues" type="{http://com.sdk.realm/RealmWillContestConsequencesDefinitionV0.0.0.1}DiceRollRangeType"/>
 *         &lt;element name="TemporaryBonus" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="DurationInRoundsOfTemporaryBounus" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WillContestConsequenceType", propOrder = {
    "description",
    "permanentBonus",
    "rollValues",
    "temporaryBonus",
    "durationInRoundsOfTemporaryBounus"
})
public class WillContestConsequenceType {

    @XmlElement(name = "Description", required = true)
    protected String description;
    @XmlElement(name = "PermanentBonus")
    protected int permanentBonus;
    @XmlElement(name = "RollValues", required = true)
    protected DiceRollRangeType rollValues;
    @XmlElement(name = "TemporaryBonus")
    protected int temporaryBonus;
    @XmlElement(name = "DurationInRoundsOfTemporaryBounus")
    protected Integer durationInRoundsOfTemporaryBounus;

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the permanentBonus property.
     * 
     */
    public int getPermanentBonus() {
        return permanentBonus;
    }

    /**
     * Sets the value of the permanentBonus property.
     * 
     */
    public void setPermanentBonus(int value) {
        this.permanentBonus = value;
    }

    /**
     * Gets the value of the rollValues property.
     * 
     * @return
     *     possible object is
     *     {@link DiceRollRangeType }
     *     
     */
    public DiceRollRangeType getRollValues() {
        return rollValues;
    }

    /**
     * Sets the value of the rollValues property.
     * 
     * @param value
     *     allowed object is
     *     {@link DiceRollRangeType }
     *     
     */
    public void setRollValues(DiceRollRangeType value) {
        this.rollValues = value;
    }

    /**
     * Gets the value of the temporaryBonus property.
     * 
     */
    public int getTemporaryBonus() {
        return temporaryBonus;
    }

    /**
     * Sets the value of the temporaryBonus property.
     * 
     */
    public void setTemporaryBonus(int value) {
        this.temporaryBonus = value;
    }

    /**
     * Gets the value of the durationInRoundsOfTemporaryBounus property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getDurationInRoundsOfTemporaryBounus() {
        return durationInRoundsOfTemporaryBounus;
    }

    /**
     * Sets the value of the durationInRoundsOfTemporaryBounus property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setDurationInRoundsOfTemporaryBounus(Integer value) {
        this.durationInRoundsOfTemporaryBounus = value;
    }

}
