//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.06.07 at 09:50:47 PM CDT 
//


package com.sdk.realm.willcontest.consequence.persistance;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for WillContestConsequenceLibraryType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WillContestConsequenceLibraryType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="WillContestConsequenceCollection" type="{http://com.sdk.realm/RealmWillContestConsequencesDefinitionV0.0.0.1}WillContestConsequenceCollectionType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WillContestConsequenceLibraryType", propOrder = {
    "willContestConsequenceCollection"
})
public class WillContestConsequenceLibraryType {

    @XmlElement(name = "WillContestConsequenceCollection", required = true)
    protected WillContestConsequenceCollectionType willContestConsequenceCollection;

    /**
     * Gets the value of the willContestConsequenceCollection property.
     * 
     * @return
     *     possible object is
     *     {@link WillContestConsequenceCollectionType }
     *     
     */
    public WillContestConsequenceCollectionType getWillContestConsequenceCollection() {
        return willContestConsequenceCollection;
    }

    /**
     * Sets the value of the willContestConsequenceCollection property.
     * 
     * @param value
     *     allowed object is
     *     {@link WillContestConsequenceCollectionType }
     *     
     */
    public void setWillContestConsequenceCollection(WillContestConsequenceCollectionType value) {
        this.willContestConsequenceCollection = value;
    }

}
