//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.06.07 at 09:50:47 PM CDT 
//


package com.sdk.realm.willcontest.consequence.persistance;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for WillContestConsequenceCollectionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WillContestConsequenceCollectionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="WillContestConsequence" type="{http://com.sdk.realm/RealmWillContestConsequencesDefinitionV0.0.0.1}WillContestConsequenceType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WillContestConsequenceCollectionType", propOrder = {
    "willContestConsequence"
})
public class WillContestConsequenceCollectionType {

    @XmlElement(name = "WillContestConsequence")
    protected List<WillContestConsequenceType> willContestConsequence;

    /**
     * Gets the value of the willContestConsequence property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the willContestConsequence property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWillContestConsequence().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link WillContestConsequenceType }
     * 
     * 
     */
    public List<WillContestConsequenceType> getWillContestConsequence() {
        if (willContestConsequence == null) {
            willContestConsequence = new ArrayList<WillContestConsequenceType>();
        }
        return this.willContestConsequence;
    }

}
