//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.08.17 at 10:08:45 PM CDT 
//


package com.sdk.realm.spell.persistance;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.sdk.realm.spell.persistance package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _SpellLibrary_QNAME = new QName("http://com.sdk.realm/RealmSpellsDefinitionV0.0.0.1", "SpellLibrary");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.sdk.realm.spell.persistance
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SpellCollectionType }
     * 
     */
    public SpellCollectionType createSpellCollectionType() {
        return new SpellCollectionType();
    }

    /**
     * Create an instance of {@link SpellType }
     * 
     */
    public SpellType createSpellType() {
        return new SpellType();
    }

    /**
     * Create an instance of {@link SpellLibraryType }
     * 
     */
    public SpellLibraryType createSpellLibraryType() {
        return new SpellLibraryType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SpellLibraryType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.sdk.realm/RealmSpellsDefinitionV0.0.0.1", name = "SpellLibrary")
    public JAXBElement<SpellLibraryType> createSpellLibrary(SpellLibraryType value) {
        return new JAXBElement<SpellLibraryType>(_SpellLibrary_QNAME, SpellLibraryType.class, null, value);
    }

}
