//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.08.17 at 10:08:45 PM CDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://com.sdk.realm/RealmSpellsDefinitionV0.0.0.1", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.sdk.realm.spell.persistance;
