//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.08.17 at 10:08:45 PM CDT 
//


package com.sdk.realm.spell.persistance;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SpellLibraryType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SpellLibraryType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="HerbCollection" type="{http://com.sdk.realm/RealmSpellsDefinitionV0.0.0.1}SpellCollectionType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SpellLibraryType", propOrder = {
    "herbCollection"
})
public class SpellLibraryType {

    @XmlElement(name = "HerbCollection", required = true)
    protected SpellCollectionType herbCollection;

    /**
     * Gets the value of the herbCollection property.
     * 
     * @return
     *     possible object is
     *     {@link SpellCollectionType }
     *     
     */
    public SpellCollectionType getHerbCollection() {
        return herbCollection;
    }

    /**
     * Sets the value of the herbCollection property.
     * 
     * @param value
     *     allowed object is
     *     {@link SpellCollectionType }
     *     
     */
    public void setHerbCollection(SpellCollectionType value) {
        this.herbCollection = value;
    }

}
